### ISSUE TITLE
mount.s3ql hangs on dugong.HostnameNotResolvable error

### ISSUE THREAD

**Issue by dgasaway** [s3ql/s3ql#100]
Running 2.8, a number of exceptions like the below occurred, I believe while data was being written to the mount:

```
Apr  4 01:47:03 wolfie mount.s3ql[29386]: Thread-5] root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/dugong/__init__.py", line 1544, in create_socket
    return socket.create_connection(address)
  File "/usr/lib64/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib64/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/s3ql/mount.py", line 64, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.6/site-packages/s3ql/block_cache.py", line 409, in _upload_loop
    self._do_upload(*tmp)
  File "/usr/lib64/python3.6/site-packages/s3ql/block_cache.py", line 436, in _do_upload
    % obj_id).get_obj_size()
  File "/usr/lib64/python3.6/site-packages/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/lib64/python3.6/site-packages/s3ql/backends/common.py", line 340, in perform_write
    return fn(fh)
  File "/usr/lib64/python3.6/site-packages/s3ql/backends/comprenc.py", line 371, in __exit__
    self.close()
  File "/usr/lib64/python3.6/site-packages/s3ql/backends/comprenc.py", line 365, in close
    self.fh.close()
  File "/usr/lib64/python3.6/site-packages/s3ql/backends/comprenc.py", line 530, in close
    self.fh.close()
  File "/usr/lib64/python3.6/site-packages/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/lib64/python3.6/site-packages/s3ql/backends/s3c.py", line 948, in close
    headers=self.headers, body=self.fh)
  File "/usr/lib64/python3.6/site-packages/s3ql/backends/gs.py", line 188, in _do_request
    query_string=query_string, body=body)
  File "/usr/lib64/python3.6/site-packages/s3ql/backends/s3c.py", line 480, in _do_request
    query_string=query_string, body=body)
  File "/usr/lib64/python3.6/site-packages/s3ql/backends/s3c.py", line 718, in _send_request
    headers=headers, body=BodyFollowing(body_len))
  File "/usr/lib64/python3.6/site-packages/dugong/__init__.py", line 569, in send_request
    self.timeout)
  File "/usr/lib64/python3.6/site-packages/dugong/__init__.py", line 1495, in eval_coroutine
    if not next(crt).poll(timeout=timeout):
  File "/usr/lib64/python3.6/site-packages/dugong/__init__.py", line 596, in co_send_request
    self.connect()
  File "/usr/lib64/python3.6/site-packages/dugong/__init__.py", line 490, in connect
    self._sock = create_socket((self.hostname, self.port))
  File "/usr/lib64/python3.6/site-packages/dugong/__init__.py", line 1548, in create_socket
    raise HostnameNotResolvable(address[0])
dugong.HostnameNotResolvable: Host commondatastorage.googleapis.com does not have any ip addresses
```

When I discovered this later in the morning, I attempted various commands like 'ls' and 's3qlstat', but they would all hang on IO waits.  'fusermount -u' would simply complain that the filesystem was in use.  I had too use 'kill -9' on mount.s3ql, then 'fusermount -u', and finally, 'fsck.s3ql'.  Everything seemed fine, with fsck was uploading dirty blocks, then this...

```
Apr  4 09:26:44 wolfie fsck.s3ql[32519]: MainThread] s3ql.fsck.log_error: Writing dirty block 1 of inode 556620 to backend
Apr  4 09:26:44 wolfie fsck.s3ql[32519]: MainThread] s3ql.fsck.log_error: Writing dirty block 0 of inode 556610 to backend
Apr  4 09:30:06 wolfie fsck.s3ql[32519]: MainThread] s3ql.fsck.log_error: Writing dirty block 0 of inode 556612 to backend
Apr  4 09:33:27 wolfie fsck.s3ql[32519]: MainThread] s3ql.fsck.log_error: Writing dirty block 1 of inode 556616 to backend
Apr  4 09:36:19 wolfie fsck.s3ql[32519]: MainThread] s3ql.fsck.log_error: Writing dirty block 1 of inode 556610 to backend
Apr  4 09:39:40 wolfie fsck.s3ql[32519]: MainThread] s3ql.fsck.check: Dropping temporary indices...
Apr  4 09:39:40 wolfie fsck.s3ql[32519]: MainThread] root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/fsck.s3ql", line 11, in <module>
    load_entry_point('s3ql==2.28', 'console_scripts', 'fsck.s3ql')()
  File "/usr/lib64/python3.6/site-packages/s3ql/fsck.py", line 1322, in main
    fsck.check()
  File "/usr/lib64/python3.6/site-packages/s3ql/fsck.py", line 78, in check
    self.check_cache()
  File "/usr/lib64/python3.6/site-packages/s3ql/fsck.py", line 195, in check_cache
    raise RuntimeError('Strange file in cache directory: %s' % filename)
RuntimeError: Strange file in cache directory: 550328-1.tmp
```

**Comment by Nikratio** [comment]
Sorry for the delayed response. It should be fine to delete this file, it is created when mount.s3ql attempts to download data from the backend. In almost all cases, this is cleaned up automatically, but a `kill -9` doesn't allow for that.

For the record, a better way to clean the mountpoint is to run `echo 1 > /sys/fs/fuse/connections/<number>/abort`. But this should never be necessary.

**Comment by Nikratio** [comment]
Are you able to reproduce this issue? You should be able to reproduce the failure mode by mounting the file system and then changing the nameserver in `/etc/resolv.conf` to something that does not exist.

If you are able to reproduce it, can you confirm that the process continues to hang even if you undo the changes to `resolv.conf`?

**Comment by dgasaway** [comment]
It has occurred several times since I opened the bug.  In fact, it happened just yesterday - the hang, that is, no "strange file".  It's not clear what you'd want me to test if I did intentionally reproduce.  You are wondering if the hung processes will unhang if I reverse the changes to resolv.conf?  I can say that the past hangs start during network outages, and hang indefinitely, even after the network is restored.

**Comment by Nikratio** [comment]
And there are no log entries besides the one that you posted above? 

Could you please send SIGUSR1 to the mount.s3ql process when it hangs? This should result in entries in the mount.s3ql_crit file (or something like it), and post this here?

**Comment by dgasaway** [comment]
Okay, I will try to do that.  I looked through the logs from the hang I fixed yesterday, and there are some additional errors.  Unfortunately, I don't quite remember what manual interventions I took and when.  Apparently, it was hung for more than 4 days - I was on holiday, out of town, and checking on it only intermittently.  So, let me try to get better information for you.

**Comment by dgasaway** [comment]
I had a bit of a different situation today.  A `s3qlctrl flushcache` command was still running, but was no longer attempting to write the dirty blocks.  I used the `echo 1 >` command you suggested, which ended the s3qlctrl process, but left the mount.s3ql process running.  New commands resulted in "Transport endpoint not connected."  So I used `fusermount -u`, which would usually end mount.s3ql in my experience.  But today, mount.s3ql kept running, and commands resulted in "BusyError: database is locked".  Then I used `kill -9` followed by `fsck.s3ql`.  I didn't try the SUGUSR1 since it's a different issue; I just wanted to let you know how the `echo 1>` worked out.

**Comment by dgasaway** [comment]
No good repro, yet.  I should point out that I have network problems frequently during backup hours lately (unreliable service provider), but most of the time mount.s3ql ends on its own.  I don't think I can repro at will.

**Comment by dgasaway** [comment]
Reproduced this morning.  At this moment, I have `mount.s3ql`, `s3qlctrl flushcache`, `s3qlstat` and `ls <mountpoint>` processes that are all hung.  I'm not sure whether you want me to send SIGUSR1 to `mount.s3ql` or to `s3qctrl`.  There has been no log activity since four hours ago.  I'll attach the full log since the mount.

**Comment by dgasaway** [comment]
Since you weren't available, I went ahead and used `kill -s SIGUSR1` first on the `mount.s3ql` process, then on the `s3qlctrl` process.  Neither appeared to have any result - processes were still hung, and no additional logs were produced.  I'll have to kill the processes for now.

**Comment by Nikratio** [comment]
Are your sure? Note that extra logging is written into a different file that is normally empty. It ends in _crit.log, IIRC

**Comment by dgasaway** [comment]
I searched the entire server.  There are two such files, one in root's .s3ql folder (the user doing the mount in this case), and one in a regular user folder.  Both are zero bytes, and the newest is dated more 4 years ago.

**Comment by Nikratio** [comment]
That is very odd. So odd that I am tempted to say that your issues may not be related to S3QL at all. The handling of SIGUSR1 happens at the C level, there is no Python code nor S3QL code involved at all.

The file should be named `mount.s3ql_crit.log` and be located next to `mount.log`. Do you get output if you send SIGUSR1 to `mount.s3ql` when it is not frozen already?

**Comment by dgasaway** [comment]
No.  However, I use `--log syslog` and have a syslog-ng rule to create a log file for any s3ql process in /var/log/.  So, strictly speaking, I don't have a `mount.log` file, either.  I don't know how that affects this SIGUSR1 stuff.

**Comment by Nikratio** [comment]
That's the thing - it should not affect this at all. The new log file should appear where mount.log would appear if not using syslog.. maybe that directory is not writable?

**Comment by dgasaway** [comment]
I took out the `--log` parameter yesterday for debugging purposes, and it successfully wrote to `~/.s3ql/mount.log` today, so no... I'd say permissions are fine.  I'm just waiting on the hang to happen again to debug further.

**Comment by Nikratio** [comment]
No need to wait for the hang, please first confirm that SIGUSR1 works as excited when it is not hanging.

**Comment by dgasaway** [comment]
OK.  I mounted.  Ran `kill -s SIGUSR1 <pid>`.  Nothing logged to `mount.s3ql_crit.log`.  Only thing logged to `mount.log` was from the mount.

**Comment by dgasaway** [comment]
Oh, and `mount.s3ql` is still running, if that matters.

**Comment by dgasaway** [comment]
Another hang this morning.  By the way, I just noticed that I mistyped the version #.  This is v2.28, not v2.8.  That's the newest version in the funtoo repos.  I could get the v2.33 ebuild from gentoo.  Better yet, I could install v3.2 from source.  I'll wait a little while, though, in case you want to keep trying to debug v2.28.

**Comment by Nikratio** [comment]
To be honest, I don't know what else to do here. The functionality that doesn't seem to be working is not implemented in S3QL but in core Python. As long as this doesn't work, I don't see much point investigating anything else. 

Here is what it should look like:

```
$ mount.s3ql --version
S3QL 3.0

$ ls -l ~/.s3ql/mount.s3ql*
/bin/ls: cannot access '/home/nikratio/.s3ql/mount.s3ql*': No such file or directory

$ mount.s3ql local://bucket mnt/ --quiet
$ killall -USR1 mount.s3ql
$ ls -l ~/.s3ql/mount.s3ql*
-rw-r--r-- 1 nikratio nikratio 7593 Aug  2 11:16 /home/nikratio/.s3ql/mount.s3ql_crit.log

$ head ~/.s3ql/mount.s3ql_crit.log 
Thread 0x00007fbd1affd700 (most recent call first):

Thread 0x00007fbd1b7fe700 (most recent call first):

Thread 0x00007fbd1bfff700 (most recent call first):

Thread 0x00007fbd20ff9700 (most recent call first):

Thread 0x00007fbd217fa700 (most recent call first):
$ fusermount -u mnt
```

**Comment by dgasaway** [comment]
I tried your exact commands on another system...

```
[dave@chopin ~]$ mount.s3ql --version
S3QL 2.33
[dave@chopin ~]$ ls -l ~/.s3ql/mount.s3ql*
ls: cannot access '/home/dave/.s3ql/mount.s3ql*': No such file or directory
[dave@chopin ~]$ mount.s3ql local://bucket mnt/ --quiet
Enter file system encryption passphrase:
[dave@chopin ~]$ killall -USR1 mount.s3ql
[dave@chopin ~]$ ls -l ~/.s3ql/mount.s3ql*
-rw------- 1 dave dave 0 Aug  2 08:25 /home/dave/.s3ql/mount.s3ql_crit.log
[dave@chopin ~]$ head ~/.s3ql/mount.s3ql_crit.log
[dave@chopin ~]$ fusermount -u mnt

**Comment by dgasaway** [comment]
Since the handling is set up differently (without a file argument) with `--fg`, I tried that too.

```
[dave@chopin ~]$ mount.s3ql --version
S3QL 2.33
[dave@chopin ~]$ ls -l ~/.s3ql/mount.s3ql*
ls: cannot access '/home/dave/.s3ql/mount.s3ql*': No such file or directory
[dave@chopin ~]$ mount.s3ql local://bucket mnt/ --quiet --fg
Enter file system encryption passphrase:
```

Then in another terminal:
```
[dave@chopin ~]$ killall -USR1 mount.s3ql
[dave@chopin ~]$ ls -l ~/.s3ql/mount.s3ql*
ls: cannot access '/home/dave/.s3ql/mount.s3ql*': No such file or directory
[dave@chopin ~]$ umount.s3ql mnt/
```

Back in the first:
```
Enter file system encryption passphrase:
[dave@chopin ~]$

**Comment by Nikratio** [comment]
No idea what's happening here. Maybe try to update to the newest version?

**Comment by dgasaway** [comment]
I want to share some more experience with this, in case it fills in some gaps.  I'm still not on 3.x, unfortunately, but at 2.33 now.  What happened today seemed different, but makes we wonder if I didn't misinterpret the earlier events.  `s3qlstat` and `ls` hung, but s3ql still seemed to be uploading as the result of a `s3qlctrl flushcache` operation.  So, I let things be.  After a few more hours (enough time to upload dirty blocks, I would assume), `s3qlctrl flushcache` ended with normal exit code.  The script then proceeded to issue `umount.s3ql` which reported this:
```
Mar  4 12:57:49 wolfie mount.s3ql[18897]: MainThread] s3ql.mount.unmount: Unmounting file system...
Mar  4 12:57:49 wolfie mount.s3ql[18897]: MainThread] root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/mount.s3ql", line 11, in <module>
    load_entry_point('s3ql==2.33', 'console_scripts', 'mount.s3ql')()
  File "/usr/lib64/python3.6/site-packages/s3ql/mount.py", line 221, in main
    raise RuntimeError('Received signal %d, terminating' % (ret,))
RuntimeError: Received signal 15, terminating
```
I did not send SIGTERM to mount.s3ql.  Somewhere in the proceedings, the hung commands reported `Software caused connection abort`.  After `fusermount -u`, I ran an `fsck.s3ql`, which reported no issues and normal exit code, as though the whole process completed successfully despite the exception reported.

Does that make any more sense?

**Comment by dgasaway** [comment]
I'm closing this.  I'm running a newer version now, and haven't experienced the original problem in some time.  I'm possibly experiencing something like what I last described, right now, but I've decided to take the 's3qlctrl flushcache' out of the script to see if that makes any difference.
