### ISSUE TITLE
s3ql showing error while trying to install

### ISSUE THREAD

**Issue by prakash271989** [s3ql/s3ql#104]
python3 setup.py install
MANIFEST.in exists, running in developer mode
running install
running bdist_egg
running egg_info
writing src/s3ql.egg-info/PKG-INFO
writing dependency_links to src/s3ql.egg-info/dependency_links.txt
writing entry points to src/s3ql.egg-info/entry_points.txt
writing requirements to src/s3ql.egg-info/requires.txt
writing top-level names to src/s3ql.egg-info/top_level.txt
reading manifest file 'src/s3ql.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no directories found matching 'doc'
warning: no files found matching 'INSTALL.txt'
warning: no files found matching 'README.txt'
no previously-included directories found matching 'tests/.cache'
no previously-included directories found matching 'doc/doctrees'
no previously-included directories found matching 'src/dugong'
no previously-included directories found matching 'doc/man/.doctrees'
no previously-included directories found matching 'doc/html/.doctrees'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.log' found anywhere in distribution
writing manifest file 'src/s3ql.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 's3ql.deltadump' extension
gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.6m -c src/s3ql/deltadump.c -o build/temp.linux-x86_64-3.6/src/s3ql/deltadump.o -Wall -Wextra -Wconversion -Wsign-compare -Werror -Werror=conversion -Werror=sign-compare -Wno-unused-function
src/s3ql/deltadump.c: In function ‘__pyx_pw_4s3ql_9deltadump_5load_table’:
src/s3ql/deltadump.c:7184:48: error: ‘__pyx_v_int64’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
                 __pyx_v_int64 = (__pyx_v_int64 + ((__pyx_cur_scope->__pyx_v_col_args[__pyx_v_j]) + (__pyx_cur_scope->__pyx_v_int64_prev[__pyx_v_j])));
                                                ^
src/s3ql/deltadump.c:5911:11: note: ‘__pyx_v_int64’ was declared here
   int64_t __pyx_v_int64;
           ^
src/s3ql/deltadump.c:12045:13: error: ‘__pyx_v_row_count’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
             return PyInt_FromLong((long) value);
             ^
src/s3ql/deltadump.c:5910:11: note: ‘__pyx_v_row_count’ was declared here
   int64_t __pyx_v_row_count;
           ^
cc1: all warnings being treated as errors
error: command 'gcc' failed with exit status 1
#

**Comment by Nikratio** [comment]
Thanks for the report! If you want to work on this, I'm happy to review pull requests. If not, I suggest using a release tarball instead of trying to compile from Git (see README)
