### ISSUE TITLE
authinfo2 documentation

### ISSUE THREAD

**Issue by Uplink03** [s3ql/s3ql#111]
UPDATED: I found the documentation in [Storing Backend Information](http://www.rath.org/s3ql-docs/authinfo.html) now.

It could mention `~/.s3ql/authinfo2` so it appears in searches.

ORIGINAL:
I see ~/.s3ql/authinfo2 mentioned in the man pages, but the file itself is not documented. I looked in the User Guide, in the Wiki, and the source code and I had to piece one together from tangent information:

```
[s3-some-identifier]
backend-login: S3_key_ID
backend-password: S3_secret_key
storage-url: s3://zone/bucket
```

The first three lines are inspired from the "running tests" section of the User Guide. The `storage-url` is from reading the parser for that file and noticing it's skipping over any section that doesn't have it.

**Comment by Nikratio** [comment]
Closing per updated description.
