### ISSUE TITLE
Inaccurate Amazon S3 US standard region warning in documentation

### ISSUE THREAD

**Issue by JustinLovinger** [s3ql/s3ql#114]
The documentation [here](http://www.rath.org/s3ql-docs/backends.html#amazon-s3) states "it is recommend to create the bucket in the geographically closest storage region, but not the US Standard region (see Important Rules to Avoid Losing Data for the reason)."

And the page on [Important Rules to Avoid Losing Data](http://www.rath.org/s3ql-docs/durability.html#consistency-window-list) states that Amazon S3 in the US standard region has no consistency guarantee.

However, Amazon [has provided read-after-write consistency in the US standard region since 2015](https://aws.amazon.com/about-aws/whats-new/2015/08/amazon-s3-introduces-new-usability-enhancements/). Therefore, the warning against using US standard region and the consistency chart for US standard region is no longer accurate.

**Comment by Nikratio** [comment]
Thanks for the report! Would you mind submitting a pull request to update this?
