### ISSUE TITLE
copies files being inappropriately locked

### ISSUE THREAD

**Issue by mauricev** [s3ql/s3ql#123]
I'm testing using s3ql as a backend to nextcloud. I copy a file and it "copies" within the context of nextcloud. Then some sort of post-processing takes place. During this time, nextcloud reports the error

`root/files/sol-10-u11-ga-x86-dvd.iso.upload.part" is locked`

**Comment by Nikratio** [comment]
I'm afraid I do not understand what you are trying to say. I strongly suspect, however, that this is not a bug in S3QL but a question about how it works. I would recommend to ask it on the S3QL mailing list instead. To subscribe, send an email to `s3ql+subscribe@googlegroups.com`. After that you can post your question by sending it to `s3ql@googlegroups.com`. Alternatively, you can subscribe and access the list online at https://groups.google.com/d/forum/s3ql.

In either case, please use the search function before you ask a question - it may have been asked and answered before. Thanks!
