### ISSUE TITLE
Crashes when server sends malformed error message

### ISSUE THREAD

**Issue by eli-kaplan** [s3ql/s3ql#124]
Running into an issue using S3QL with Wasabi S3. 

It seems that every so often (only seems to happen when data is currently being uploaded) the S3 connection will degrade (can't tell if it's dropping, timing out, being rate limited, etc. just from the logs) and seemingly as a result the S3QL mount will crash and not restart, causing all data uploaded since the last metadata sync to be lost. 

Here's what ends up in `syslog`:

```
Oct  4 06:53:36 File mount.s3ql[18910:Thread-9] s3ql.backends.common.wrapped: Encountered ConnectionTimedOut (send/recv timeout exceeded), retrying ObjectW.close (attempt 4)...
Oct  4 06:53:44 File mount.s3ql[18910:Thread-4] s3ql.backends.common.wrapped: Encountered ConnectionTimedOut (send/recv timeout exceeded), retrying ObjectW.close (attempt 11)...
Oct  4 06:53:46 File mount.s3ql[18910:Thread-5] s3ql.backends.common.wrapped: Encountered ConnectionTimedOut (send/recv timeout exceeded), retrying ObjectW.close (attempt 9)...
Oct  4 06:53:49 File mount.s3ql[18910:Thread-10] s3ql.backends.common.wrapped: Encountered ConnectionTimedOut (send/recv timeout exceeded), retrying ObjectW.close (attempt 11)...
Oct  4 06:54:16 File mount.s3ql[18910:Thread-9] s3ql.backends.common.wrapped: Encountered ConnectionTimedOut (send/recv timeout exceeded), retrying ObjectW.close (attempt 5)...
```

And a bit over 12 hours later, with no errors in the interim:

```
Oct  4 19:15:27 File mount.s3ql[18910:Thread-10] root.excepthook: Uncaught top-level exception:#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/mount.py", line 58, in run_with_except_hook#012    run_old(*args, **kw)#012  File "/usr/lib/python3.6/threading.py", line 864, in run#012    self._target(*self._args, **self._kwargs)#012  File "/usr/local/lib/
python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/block_cache.py", line 446, in _upload_loop#012    self._do_upload(*tmp)#012  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/block_cache.py", line 473, in _do_upload#012    % obj_id).get_obj_size()#012  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/backends/common.py", line 108, in wrapped#012    r
eturn method(*a, **kw)#012  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/backends/common.py", line 279, in perform_write#012    return fn(fh)#012  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/backends/comprenc.py", line 389, in __exit__#012    self.close()#012  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/backends/com
prenc.py", line 383, in close#012    self.fh.close()#012  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/backends/comprenc.py", line 548, in close#012    self.fh.close()#012  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/backends/common.py", line 108, in wrapped#012    return method(*a, **kw)#012  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-
linux-x86_64.egg/s3ql/backends/s3c.py", line 910, in close#012    headers=self.headers, body=self.fh)#012  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/backends/s3c.py", line 528, in _do_request#012    self._parse_error_response(resp)#012  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/backends/s3c.py", line 548, in _parse_error_response#012    if not XML_
CONTENT_RE.match(content_type) or resp.length == 0:#012TypeError: expected string or bytes-like object
Oct  4 19:15:27 File mount.s3ql[18910:Thread-6] s3ql.mount.exchook: Unhandled top-level exception during shutdown (will not be re-raised)
```

This error is repeated a few times, then about an hour later:
```
Oct  4 20:33:29 File mount.s3ql[18910:MainThread] s3ql.mount.unmount: Unmounting file system...
Oct  4 20:33:29 File mount.s3ql[18910:MainThread] root.excepthook: Uncaught top-level exception:#012Traceback (most recent call last):#012  File "/usr/local/bin/mount.s3ql", line 11, in <module>#012    load_entry_point('s3ql==3.3', 'console_scripts', 'mount.s3ql')()#012  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/mount.py", line 214, in main#012    raise RuntimeError('Received signal %d,
terminating' % (ret,))#012RuntimeError: Received signal 15, terminating
```

As a result, after this error, the mount point can no longer be accessed, with a standard `Transport endpoint not connected` error. To make the mount functional again, I then have to run `fsck.s3ql`, which ends up deleting all of the data uploaded since the last metadata sync (which I have at the default 24-hour period) - which is quite inconvenient as Wasabi bills deleted data for three months. Data uploaded before the last metadata sync is unaffected.

Using S3QL 3.3 on Ubuntu 18.04.

**Comment by eli-kaplan** [comment]
Just crashed again - luckily had nothing uploaded after the most recent metadata sync. Here is what caused it this time:

```
Oct 13 05:11:48 File mount.s3ql[2252:fuse-worker-14] llfuse.(unknown function): handler raised <class 'AttributeError'> exception ('NoneType' object has no attribute 'endswith'), terminating main loop.
Oct 13 05:11:50 File mount.s3ql[2252:MainThread] s3ql.mount.unmount: Unmounting file system...
Oct 13 05:11:50 File mount.s3ql[2252:MainThread] root.excepthook: Uncaught top-level exception:#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.e
gg/s3ql/block_cache.py", line 809, in _get_entry#012    el = self.cache[(inode, blockno)]#012KeyError: (370, 4)#012#012During handling of the above exception, another exception occurred:#012#012Traceback (most rec
ent call last):#012  File "/usr/local/bin/mount.s3ql", line 11, in <module>#012    load_entry_point('s3ql==3.3', 'console_scripts', 'mount.s3ql')()#012  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-
linux-x86_64.egg/s3ql/mount.py", line 211, in main#012    ret = llfuse.main(workers)#012  File "src/fuse_api.pxi", line 348, in llfuse.main#012  File "src/handlers.pxi", line 322, in llfuse.fuse_read#012  File "sr
c/handlers.pxi", line 323, in llfuse.fuse_read#012  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/fs.py", line 1041, in read#012    tmp = self._readwrite(fh, offset, length=leng
th)#012  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/fs.py", line 1118, in _readwrite#012    with self.cache.get(id_, blockno) as fh:#012  File "/usr/lib/python3.6/contextlib.
py", line 81, in __enter__#012    return next(self.gen)#012  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/block_cache.py", line 788, in get#012    el = self._get_entry(inode, b
lockno)#012  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/block_cache.py", line 844, in _get_entry#012    backend.perform_read(do_read, 's3ql_data_%d' % obj_id)#012  File "/usr
/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/backends/common.py", line 108, in wrapped#012    return method(*a, **kw)#012  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-lin
ux-x86_64.egg/s3ql/backends/common.py", line 256, in perform_read#012    fh = self.open_read(key)#012  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/backends/comprenc.py", line
194, in open_read#012    fh = self.backend.open_read(key)#012  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/backends/common.py", line 108, in wrapped#012    return method(*a, *
*kw)#012  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/backends/s3c.py", line 320, in open_read#012    resp = self._do_request('GET', '/%s%s' % (self.prefix, key))#012  File "/
usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/backends/s3c.py", line 528, in _do_request#012    self._parse_error_response(resp)#012  File "/usr/local/lib/python3.6/dist-packages/s3ql-
3.3-py3.6-linux-x86_64.egg/s3ql/backends/s3c.py", line 562, in _parse_error_response#012    raise get_S3Error(tree.findtext('Code'), tree.findtext('Message'), resp.headers)#012  File "/usr/local/lib/python3.6/dist
-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/backends/s3c.py", line 946, in get_S3Error#012    if code.endswith('Error'):#012AttributeError: 'NoneType' object has no attribute 'endswith'
```
Looking at the Wasabi S3 server status right now, there appears to be a restricted ingest rate and degraded performance on "some files" in the region I am connected to. This could potentially be a cause of this - although it would indicate a lack of error checking in the above referenced code. If I get a chance, I'll debug it further.

**Comment by eli-kaplan** [comment]
Did some further debugging and looked through the relevant code.

It appears that the Wasabi S3 endpoints are sporadically returning `HTTP 503` during uploads - which I suspect might be to rate-limit during times of restricted ingest rate (such as now, as of writing). Could also be something else on Wasabi's end - as it's happening on `GET` requests as well (such as in the above stacktrace).

Regardless, it seems that in this error case, the response body is XML content, but isn't matching up with the format expected by the `s3c` backend's error parser (i.e. `tree.findtext('Code')`) on the response body returns `None`).

As I see it, the easiest way to mitigate this would be to update `_parse_error_response` in `backends/s3c.py` to first check if the XML is formatted as expected, before calling `get_S3Error`. If, in this case, we simply raise a HTTPError (as in the condition where the response body is empty / not XML), I suspect the error would be handled properly. 

If I have time at some point to implement/test this fix, I'll submit a PR.

**Comment by Nikratio** [comment]
That would be great, thanks for investigating!

**Comment by ainiml** [comment]
I'm also having similar issues with Wasabi S3 and s3ql. I haven't done any investigation, but this sounds pretty solid

s3ql: `File system appears to have crashed`

**Comment by ainiml** [comment]
> Just crashed again - luckily had nothing uploaded after the most recent metadata sync. Here is what caused it this time:
> 
> ```
> Oct 13 05:11:48 File mount.s3ql[2252:fuse-worker-14] llfuse.(unknown function): handler raised <class 'AttributeError'> exception ('NoneType' object has no attribute 'endswith'), terminating main loop.
> Oct 13 05:11:50 File mount.s3ql[2252:MainThread] s3ql.mount.unmount: Unmounting file system...
> Oct 13 05:11:50 File mount.s3ql[2252:MainThread] root.excepthook: Uncaught top-level exception:#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.e
> gg/s3ql/block_cache.py", line 809, in _get_entry#012    el = self.cache[(inode, blockno)]#012KeyError: (370, 4)#012#012During handling of the above exception, another exception occurred:#012#012Traceback (most rec
> ent call last):#012  File "/usr/local/bin/mount.s3ql", line 11, in <module>#012    load_entry_point('s3ql==3.3', 'console_scripts', 'mount.s3ql')()#012  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-
> linux-x86_64.egg/s3ql/mount.py", line 211, in main#012    ret = llfuse.main(workers)#012  File "src/fuse_api.pxi", line 348, in llfuse.main#012  File "src/handlers.pxi", line 322, in llfuse.fuse_read#012  File "sr
> c/handlers.pxi", line 323, in llfuse.fuse_read#012  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/fs.py", line 1041, in read#012    tmp = self._readwrite(fh, offset, length=leng
> th)#012  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/fs.py", line 1118, in _readwrite#012    with self.cache.get(id_, blockno) as fh:#012  File "/usr/lib/python3.6/contextlib.
> py", line 81, in __enter__#012    return next(self.gen)#012  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/block_cache.py", line 788, in get#012    el = self._get_entry(inode, b
> lockno)#012  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/block_cache.py", line 844, in _get_entry#012    backend.perform_read(do_read, 's3ql_data_%d' % obj_id)#012  File "/usr
> /local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/backends/common.py", line 108, in wrapped#012    return method(*a, **kw)#012  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-lin
> ux-x86_64.egg/s3ql/backends/common.py", line 256, in perform_read#012    fh = self.open_read(key)#012  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/backends/comprenc.py", line
> 194, in open_read#012    fh = self.backend.open_read(key)#012  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/backends/common.py", line 108, in wrapped#012    return method(*a, *
> *kw)#012  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/backends/s3c.py", line 320, in open_read#012    resp = self._do_request('GET', '/%s%s' % (self.prefix, key))#012  File "/
> usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/backends/s3c.py", line 528, in _do_request#012    self._parse_error_response(resp)#012  File "/usr/local/lib/python3.6/dist-packages/s3ql-
> 3.3-py3.6-linux-x86_64.egg/s3ql/backends/s3c.py", line 562, in _parse_error_response#012    raise get_S3Error(tree.findtext('Code'), tree.findtext('Message'), resp.headers)#012  File "/usr/local/lib/python3.6/dist
> -packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/backends/s3c.py", line 946, in get_S3Error#012    if code.endswith('Error'):#012AttributeError: 'NoneType' object has no attribute 'endswith'
> ```
> 
> Looking at the Wasabi S3 server status right now, there appears to be a restricted ingest rate and degraded performance on "some files" in the region I am connected to. This could potentially be a cause of this - although it would indicate a lack of error checking in the above referenced code. If I get a chance, I'll debug it further.

Also receiving `AttributeError: 'NoneType' object has no attribute 'endswith'` at this moment

**Comment by crypdick** [comment]
@eli-kaplan I'm having this same issue D:< Crash happened in the middle of moving data into s3ql. I don't see any messages in syslog, though.

Can you tell me about metadata syncing? Is it client-side or wasabi-side? Should I wait a day before running fsck.s3ql?

**Comment by crypdick** [comment]
Even with metadata-upload-interval=1, my Wasabi-backed mounts are crashing daily.

**Comment by Nikratio** [comment]
I'm closing this issue for now. Please note that this isn't meant to imply that you haven't found a valid bug or potential improvement - you most likely have and I'm grateful that you took the time to report it.

Unfortunately, this project does not currently have any active, regular contributors or developers. The current maintainer continues to apply pull requests and tries to make regular releases, but unfortunately has no capacity to do any development beyond addressing high-impact issues. Any other reports are therefore likely to languish unless they come together with a high-quality pull request.

This report unfortunately does not fall into either category, so with the current state of affairs it's unlikely that anyone is going to be able to do anything but this anytime soon, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of all known/potential issues).
