### ISSUE TITLE
--systemd option results in failure

### ISSUE THREAD

**Issue by drgrumpy** [s3ql/s3ql#127]
With my very limited knowledge of, trying to implement automounting using systemd  on centos 7 server:

If I add the --systemd option to mount it fails:

Nov 07 15:40:11 vs01 s3ql-mount-test.sh[850]: load_entry_point('s3ql==3.3.2', 'console_scripts', 'mount.s3ql')()
Nov 07 15:40:11 vs01 s3ql-mount-test.sh[850]: File "/usr/local/lib64/python3.6/site-packages/s3ql-3.3.2-py3.6-linux-x86_64.egg/s3ql/mount.py", line 206, in main
Nov 07 15:40:11 vs01 s3ql-mount-test.sh[850]: systemd.daemon.notify('READY=1')
Nov 07 15:40:11 vs01 s3ql-mount-test.sh[850]: File "/usr/local/lib64/python3.6/site-packages/systemd/daemon.py", line 39, in notify
Nov 07 15:40:11 vs01 s3ql-mount-test.sh[850]: raise TypeError("state must be an instance of Notification")
Nov 07 15:40:11 vs01 s3ql-mount-test.sh[850]: TypeError: state must be an instance of Notification
Nov 07 15:40:11 vs01 systemd[1]: s3ql.service: main process exited, code=exited, status=1/FAILURE
Nov 07 15:40:11 vs01 systemd[1]: Failed to start Mount s3ql file system.
Nov 07 15:40:11 vs01 systemd[1]: Unit s3ql.service entered failed state.
Nov 07 15:40:11 vs01 systemd[1]: s3ql.service failed.

My mount script:
```
AUTHFILE=/home/123/456/authinfo
LOGFILE=/var/log/s3ql.log
FSCK_OPTS="--log $LOGFILE --batch --authfile $AUTHFILE --backend-options=tcp-timeout=20"
# sql mount options, systemd only available in later versions...
# 2019-11-07 breaks with --systemd notification is added
MOUNT_OPTS="--log $LOGFILE --systemd --allow-other --authfile $AUTHFILE --backend-options=tcp-timeout=20 --cachesize=204800 --max-cache-entries 65536"
STORAGE_URL="swiftks://XXX"
MOUNTPOINT="/mnt/s3backup"

echo Executing fsck.s3ql $FSCK_OPTS "$STORAGE_URL"
/usr/local/bin/fsck.s3ql $FSCK_OPTS "$STORAGE_URL"
FSCK_RESULT=$?
if [[ $FSCK_RESULT != 0 && $FSCK_RESULT != 128 ]]; then
  echo "fsck.s3ql reported errors! exit code $FSCK_RESULT" >> $LOGFILE 
  exit $FSCK_RESULT
fi
echo Executing mount.s3ql $MOUNT_OPTS "$STORAGE_URL" "$MOUNTPOINT"
exec /usr/local/bin/mount.s3ql $MOUNT_OPTS "$STORAGE_URL" "$MOUNTPOINT"
```
Systemd unit file:
[Unit]
Description=Mount s3ql file system
Requires=nss-lookup.target network.target time-sync.target
After=nss-lookup.target network.target network-online.target remote-fs-pre.target time-sync.target
Conflicts=shutdown.target
ConditionPathIsDirectory=/mnt/s3backup

[Service]
Type=notify
ExecStart=/home/drgrumpy/scripts/s3ql-mount-test.sh
LimitNOFILE=66000
TimeoutStopSec=10min
TimeoutStartSec=10min

[Install]
WantedBy=multi-user.target

**Comment by Nikratio** [comment]
See http://www.rath.org/s3ql-docs/installation.html#dependencies, you've got the wrong systemd module.

**Comment by drgrumpy** [comment]
OK, thanks. Unfortunately, I can't seem to install that module....
