### ISSUE TITLE
Use stock fuse3 from Ubuntu 

### ISSUE THREAD

**Issue by szepeviktor** [s3ql/s3ql#135]
@Nikratio Would you welcome a PR getting fuse3 v3.4.1 from Ubuntu/disco (or v3.7.0 from focal)
https://packages.ubuntu.com/source/disco/fuse3
in CI/xenial?
https://github.com/s3ql/s3ql/blob/master/tests/travis-install.sh#L5-L18

**Comment by szepeviktor** [comment]
The very same way as from Debian/bullseye in my container
https://gist.github.com/szepeviktor/d89773ad3984a14f8e6d371291d4a460#file-dockerfile-L11-L19

**Comment by Nikratio** [comment]
I'm not sure what you mean with "getting fuse into into xenial" (I have no control over which FUSE packages go into Ubunu), but the answer is probably yes.
