### ISSUE TITLE
CI fails: outcome vs. attrs

### ISSUE THREAD

**Issue by szepeviktor** [s3ql/s3ql#136]
> outcome 1.0.1 has requirement attrs>=19.2.0, but you'll have attrs 18.2.0 which is incompatible.

https://travis-ci.org/s3ql/s3ql/jobs/616359971

**Comment by Nikratio** [comment]
Shouldn't this be reported (and fixed) in the outcome package?

**Comment by szepeviktor** [comment]
So you say pip should take care about this?

**Comment by szepeviktor** [comment]
Fixed in outcome v1.0.1
https://github.com/python-trio/outcome/pull/25/files
and in trio v0.13.0
https://github.com/python-trio/trio/commit/45882339d27efa9e449474f22fee1b5668aea8ba

Should we require trio >= 0.13 ?

**Comment by Nikratio** [comment]
Either that (though presumably that means we also need to fix the deprecated run_in_worker_thread() calls), or depend on the outcome package with a comment that explains that we're only depending on outcome to work around https://github.com/python-trio/outcome/pull/25/files.

**Comment by Nikratio** [comment]
I think this has been fixed in #151
