### ISSUE TITLE
Problems running s3ql with minio azure gateway

### ISSUE THREAD

**Issue by amvoegeli** [s3ql/s3ql#152]
First time submitting an issue so let me know if there is anything I am missing.

s3ql version: 3.3
minio version: RELEASE.2020-02-07T23-28-16Z

Commands to recreate:
- export MINIO_ACCESS_KEY="$AZURE-ACCOUNT_NAME"
- export MINIO_SECRET_KEY="$AZURE-ACCESS_KEY"
- minio gateway azure
- mkfs.s3ql --backend-options no-ssl --plain s3c://<minio-IP:9000>/<azure-bucket>/<prefix>
- mount.s3ql --allow-other --compress zlib --cachesize 1048576 --metadata-upload-interval 0 --backend-options no-ssl s3c://<minio-IP:9000>/<azure-bucket>/<prefix> /mnt/s3mount

Here is the output I am seeing from the mount.s3ql command:
blob_smb    | Using 2 upload threads.
blob_smb    | Autodetected 1048538 file descriptors available for cache entries
blob_smb    | ERROR: Uncaught top-level exception:
blob_smb    | Traceback (most recent call last):
blob_smb    |   File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/backends/s3c.py", line 320, in open_read
blob_smb    |     resp = self._do_request('GET', '/%s%s' % (self.prefix, key))
blob_smb    |   File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/backends/s3c.py", line 528, in _do_request
blob_smb    |     self._parse_error_response(resp)
blob_smb    |   File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/backends/s3c.py", line 562, in _parse_error_response
blob_smb    |     raise get_S3Error(tree.findtext('Code'), tree.findtext('Message'), resp.headers)
blob_smb    | s3ql.backends.s3c.NoSuchKeyError: NoSuchKey: The specified key does not exist.
blob_smb    | 
blob_smb    | During handling of the above exception, another exception occurred:
blob_smb    | 
blob_smb    | Traceback (most recent call last):
blob_smb    |   File "/usr/local/bin/mount.s3ql", line 11, in <module>
blob_smb    |     load_entry_point('s3ql==3.3', 'console_scripts', 'mount.s3ql')()
blob_smb    |   File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/mount.py", line 119, in main
blob_smb    |     backend_factory = get_backend_factory(options)
blob_smb    |   File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/common.py", line 323, in get_backend_factory
blob_smb    |     tmp_backend.fetch('s3ql_metadata')
blob_smb    |   File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/backends/common.py", line 293, in fetch
blob_smb    |     return self.perform_read(do_read, key)
blob_smb    |   File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/backends/common.py", line 108, in wrapped
blob_smb    |     return method(*a, **kw)
blob_smb    |   File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/backends/common.py", line 256, in perform_read
blob_smb    |     fh = self.open_read(key)
blob_smb    |   File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/backends/comprenc.py", line 194, in open_read
blob_smb    |     fh = self.backend.open_read(key)
blob_smb    |   File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/backends/common.py", line 108, in wrapped
blob_smb    |     return method(*a, **kw)
blob_smb    |   File "/usr/local/lib/python3.6/dist-packages/s3ql-3.3-py3.6-linux-x86_64.egg/s3ql/backends/s3c.py", line 322, in open_read
blob_smb    |     raise NoSuchObject(key)
blob_smb    | s3ql.backends.common.NoSuchObject: Backend does not have anything stored under key 's3ql_metadata'

I saw something similar was recently posted at #133 .  I wasn't sure if that was the same issue or not given that I am seeing it on the mount.s3ql command and the person that reported that issue saw it with fsck.s3ql.  I also have awscli installed and it seems to be working fine with the minio azure gateway.

**Comment by amvoegeli** [comment]
As a few more data points, I have done the following:

1. Run with the patch for #133 .  Still failed to mount.  Error message was more user friendly though as opposed to the stack trace.

2. Ran using the minio gateway to S3.  I just changed the MINIO_ACCESS_KEY, the MINIO_SECRET_KEY and ran "minio gateway s3".  All the other commands I left the same.  This ran fine and s3ql was able to complete mkfs.s3ql and mount.s3ql successfully.

**Comment by amvoegeli** [comment]
Forgot to mention.  I also ran on the latest s3ql version (3.3.2) and saw the same error when attempting to mount with the minio azure gateway.  The minio s3 gateway mounted without error.

**Comment by Nikratio** [comment]
Thanks for taking the time to report this issue!
 
I'm afraid it's unlikely that someone will look into this anytime soon. There has not been much active development of S3QL for quite some time - for most users it does what they need it to do. If issues are encountered, then they are either fixed by the people who are annoyed by them, or they tend to remain open.

This is just to calibrate expectations. I am grateful that you took the time to report this and make S3QL better. I'll leave this issue open to document the problem and who knows, maybe someone will pick it up after all :-).

**Comment by amvoegeli** [comment]
No worries.  Thanks for the update and thanks for such an awesome product!

**Comment by Nikratio** [comment]
I'm closing this issue for now. Please note that this isn't meant to imply that you haven't found a valid bug or potential improvement - you most likely have and I'm grateful that you took the time to report it.

Unfortunately, this project does not currently have any active, regular contributors or developers. The current maintainer continues to apply pull requests and tries to make regular releases, but unfortunately has no capacity to do any development beyond addressing high-impact issues. Any other reports are therefore likely to languish unless they come together with a high-quality pull request.

This report unfortunately does not fall into either category, so with the current state of affairs it's unlikely that anyone is going to be able to do anything but this anytime soon, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues).
