### ISSUE TITLE
s3ql uses significantly more space for the cache than requested

### ISSUE THREAD

**Issue by vthriller** [s3ql/s3ql#153]
While mounting with `--cachesize $(numfmt --from=iec 2M)` and a cache directory that has only 2G of space, s3ql issues a warning:

```
WARNING: Requested cache size 2048 MB, but only 1512 MB available
```

However, even if filesystem is mounted with `--cachesize $(numfmt --from=iec 1.4M)`, the act of reading 1.7M files of various sizes in 4 threads still results in ENOSPC on the mountpoint that hosts the cache, with eventual stall of s3ql.

Here's what contents of the cache dir look like in `ncdu`:

```
    1.5 GiB /local:=2F=2F=2F=2Fmnt=2F.s3ql=2F-cache
  437.7 MiB  local:=2F=2F=2F=2Fmnt=2F.s3ql=2F.db
    4.0 KiB  local:=2F=2F=2F=2Fmnt=2F.s3ql=2F.params
    0.0   B  mount.s3ql_crit.log
```

**Comment by vthriller** [comment]
Found #132 that might fix this in the future. Or result in corruption of some other sort—I'm not sure.

**Comment by Nikratio** [comment]
I wouldn't call 1.5 GB to be "significantly more" than 1.4 GB. Can you reproduce this with a smaller cachesize? How big does the cache directory (note that the *.db file is not included in this) become if you specify a maximum size of eg. 500 MB?

**Comment by vthriller** [comment]
Right now I'm doing the scan with the cache size of 1G, and slowly within 20 minutes it drifted from 500M of free space to just 60M, with `-cache` directory eventually getting to the 1.4G size mark.

**Comment by vthriller** [comment]
I didn't notice at first, but apparent size of cache directory is actually 1G. Closer inspection revealed a lot of chunks with apparent size of less than 512 bytes, which have a huge overhead. This should be easy to account for, I guess...

**Comment by vthriller** [comment]
Yep, #157 seems to fix the runaway growth of cache directory in my case, and now it stays within the limits.

**Comment by Nikratio** [comment]
Could you try to instead use the --max-cache-entries option and set it to <max-cache-size> divided by <block size of your filesystem>? I think that would be the better solution.

**Comment by vthriller** [comment]
I'm not sure if it's better. I mean that solution should work, but its ergonomics… well, it's not great. Average Joe wouldn't necessarily know what's the block size of his file system, and I don't think they would be happy to do some extra math before running `mount.s3ql`. People have greater chances of just stumbling upon `--cachesize` in the man page, saying "aha!" and just moving on than learning about this formula.
