### ISSUE TITLE
Backblaze B2 now supports S3 API - changes needed to s3ql?

### ISSUE THREAD

**Issue by brandonpoc** [s3ql/s3ql#164]
Backblaze's B2 cloud storage, now in beta, supports the S3 API. I have tested it with the 'aws s3' cmd and it seemingly works fine. I specify the endpoint URL as --endpoint-url https://s3.us-west-001.backblazeb2.com (or whatever the endpoint they give for the new bucket) and specified the keyid and secret access key in the aws configuration, gave it the bucket, and all was well.

However when I try to use s3ql via mkfs.s3ql, I get errors like this (which I suppose are from the way s3ql creates endpoint/bucket access hostnames):

mkfs.s3ql --authfile ~/.s3ql/b2info --cachedir /s3ql.cache/b2.test s3://s3.us-west-001.backblazeb2.com/my-s3ql-test-for-b2-bucket

(my b2info file has the proper access key/secret key)

I get this:

dugong.HostnameNotResolvable: Host s3-s3.us-west-002.backblazeb2.com.amazonaws.com does not have any ip addresses

Is there a way (out of the box in config) to over-ride and specify the URL without s3ql adding 's3-<..>.amazonaws.com' to it? In backend/s3.py it appears it's hardcoded in. Off the top of your heads, is there anything else aside from modifying the hostnames that might prevent this from working or, given it supports the S3 API, should it work as expected?

Thanks

**Comment by brandonpoc** [comment]
UPDATE: I replaced the s3 hostname in backend/s3.py with the correct hostname, and when creating a filesystem via mkfs.s3ql, I get the following:

```
-> # bin/mkfs.s3ql --authfile ~/.s3ql/b2info --cachedir /s3ql.cache/b2.test s3://s3.us-west-001.backblazeb2.com/my-s3ql-test-for-b2-bucket
Before using S3QL, make sure to read the user's guide, especially
the 'Important Rules to Avoid Losing Data' section.
Enter encryption password:
Confirm encryption password:
Generating random encryption key...
Creating metadata tables...
Dumping metadata...
Dumping metadata...
..objects..
..blocks..
..inodes..
..inode_blocks..
..symlink_targets..
..names..
..contents..
..ext_attributes..
Compressing and uploading metadata...
Wrote 151 bytes of compressed metadata.
Cycling metadata backups...
Backing up old metadata...
ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "bin/mkfs.s3ql", line 21, in <module>
    s3ql.mkfs.main(sys.argv[1:])
  File "/usr/local/src/s3ql-3.4.0/src/s3ql/mkfs.py", line 158, in main
    dump_and_upload_metadata(backend, db, param)
  File "/usr/local/src/s3ql-3.4.0/src/s3ql/metadata.py", line 313, in dump_and_upload_metadata
    upload_metadata(backend, fh, param)
  File "/usr/local/src/s3ql-3.4.0/src/s3ql/metadata.py", line 327, in upload_metadata
    cycle_metadata(backend)
  File "/usr/local/src/s3ql-3.4.0/src/s3ql/metadata.py", line 135, in cycle_metadata
    cycle_fn("s3ql_metadata_new", "s3ql_metadata")
  File "/usr/local/src/s3ql-3.4.0/src/s3ql/backends/comprenc.py", line 310, in copy
    self._copy_or_rename(src, dest, rename=False, metadata=metadata)
  File "/usr/local/src/s3ql-3.4.0/src/s3ql/backends/comprenc.py", line 319, in _copy_or_rename
    meta_raw = self.backend.lookup(src)
  File "/usr/local/src/s3ql-3.4.0/src/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/local/src/s3ql-3.4.0/src/s3ql/backends/s3c.py", line 294, in lookup
    return self._extractmeta(resp, key)
  File "/usr/local/src/s3ql-3.4.0/src/s3ql/backends/s3c.py", line 724, in _extractmeta
    meta = literal_eval('{ %s }' % buf)
  File "/usr/lib/python3.7/ast.py", line 91, in literal_eval
    return _convert(node_or_string)
  File "/usr/lib/python3.7/ast.py", line 79, in _convert
    map(_convert, node.values)))
  File "/usr/lib/python3.7/ast.py", line 90, in _convert
    return _convert_signed_num(node)
  File "/usr/lib/python3.7/ast.py", line 58, in _convert_signed_num
    operand = _convert_num(node.operand)
  File "/usr/lib/python3.7/ast.py", line 55, in _convert_num
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: <_ast.Str object at 0x7f86b2e182b0>

```

Is there some kind of metadata stored in something that S3 supports that B2 doesn't? Perhaps some kind of Amazon tags? Or something else here all together? I am not familiar with S3 API.

Thanks

**Comment by Nikratio** [comment]
@brandonpoc The Amazon S3 API is a moving (albeit slowly) target. The S3 backend is intended to track this API and therefore generally not suitable for anything that claims to be S3 compatible. Try the s3c backend, this is intended for this purpose. You can specify a hostname, and it only uses the basic S3 features from one of the very early API revisions.

**Comment by brandonpoc** [comment]
Thank you for holding my hand; it would have been prudent of me to have read the documentation and seen the other S3-compatible backends and the s3c code.

Much appreciated,

Brandon
