### ISSUE TITLE
Keystone v3 authentication fails with OVH object storage

### ISSUE THREAD

**Issue by redneb** [s3ql/s3ql#180]
I switched to keystone v3 authentication (from v2) today by adding the `domain=Default` option to `--backend-options` and I was getting an `AuthorizationError`:

    mount.s3ql[5453]: ERROR: No permission to access backend.

Apparently, `s3ql` is making a request to the auth server that looks like this:

    curl -i -X POST \
        -H "Content-Type: application/json" \
        -d '{"auth": {"identity": {"methods": ["password"], "password": {"user": {"name": "XXXXXXXX", "domain": {"id": "Default"}, "password": "XXXXXXXXXXXXXXXXXXXXXXXXX"}}}, "scope": {"project": {"id": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", "domain": {"id": "Default"}}}}}' \
        https://auth.cloud.ovh.net/v3/auth/tokens

and getting a response like this:

    HTTP/1.1 401 Unauthorized
    WWW-Authenticate: Keystone uri="https://auth.cloud.ovh.net"
    Vary: X-Auth-Token
    Content-Type: application/json
    Content-Length: 114
    x-openstack-request-id: req-XXX-XXX-XXX-XXX-XXX
    X-IPLB-Instance: 15245
    
    {"error": {"message": "The request you have made requires authentication.", "code": 401, "title": "Unauthorized"}}

After looking into the [official OpenStack documentation](https://docs.openstack.org/api-ref/identity/v3/index.html?expanded=password-authentication-with-unscoped-authorization-detail), I concluded that the problem is that s3ql is sending an `id` for the user domain to the server but the server expects a domain `name`. Applying the following patch solved the problem for me:

    diff --git a/src/s3ql/backends/swiftks.py b/src/s3ql/backends/swiftks.py
    index c43dd1d6..f4435606 100644
    --- a/src/s3ql/backends/swiftks.py
    +++ b/src/s3ql/backends/swiftks.py
    @@ -94,7 +94,7 @@ class Backend(swift.Backend):
                                 'user': {
                                     'name': user,
                                     'domain': {
    -                                    'id': domain
    +                                    'name': domain
                                     },
                                     'password': self.password
                                 }

I am not sure if these findings apply to all OpenStack providers.

**Comment by nand2** [comment]
Hello!

I had the same issues.. I made it work by :
 - Adding '--backend-options domain=default' to mkfs.s3ql **(Careful, 'default', not 'Default')**
 - Changing the backend-login from **tenant-name:user** to **tenant-id:user**, as explained by the [doc](http://www.rath.org/s3ql-docs/backends.html#openstack-swift).

It is now working with a vanilla S3QL 3.3.2

**Comment by d--j** [comment]
@nand2 is right – you must use `default` as domain for OVH and use the `OS_TENANT_ID` instead of `OS_TENANT_NAME`). 


Since this is not a bug of S3QL, please close this issue and move any further conversation over to the [mailing list](http://groups.google.com/group/s3ql).

**Comment by redneb** [comment]
You are right, setting `domain=default` does work. This is somewhat strange since OVH doesn't say anything about `default`, they only mention `Default`. I still suspect that the patch I posted above is correct based on the official OpenStack documentation linked in the first post. But since `domain=default` works, I will close this one for now.
