### ISSUE TITLE
Problem with s3ql and b2 cloud

### ISSUE THREAD

**Issue by estuaco** [s3ql/s3ql#190]
I search in internet and i cant connect b2 with s3ql.

Try with native b2:

 mkfs.s3ql  b2://s3.us-west-002.backblazeb2.com/xxx
No such backend: b2

And s3 compatible:

mkfs.s3ql  s3c://s3.us-west-002.backblazeb2.com/xx
Enter backend login:
Enter backend password:
Before using S3QL, make sure to read the user's guide, especially
the 'Important Rules to Avoid Losing Data' section.
ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/bin/mkfs.s3ql", line 11, in <module>
    load_entry_point('s3ql==3.3.2', 'console_scripts', 'mkfs.s3ql')()
  File "/usr/lib/s3ql/s3ql/mkfs.py", line 103, in main
    if 's3ql_metadata' in plain_backend:
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 206, in __contains__
    return self.contains(key)
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 375, in contains
    self.lookup(key)
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/lib/s3ql/s3ql/backends/s3c.py", line 286, in lookup
    resp = self._do_request('HEAD', '/%s%s' % (self.prefix, key))
  File "/usr/lib/s3ql/s3ql/backends/s3c.py", line 528, in _do_request
    self._parse_error_response(resp)
  File "/usr/lib/s3ql/s3ql/backends/s3c.py", line 545, in _parse_error_response
    raise HTTPError(resp.status, resp.reason, resp.headers)
s3ql.backends.s3c.HTTPError: 400

**Comment by powerpaul17** [comment]
You cannot use the S3 endpoint format when using the B2 backend.

If you look into the [backend documentation](https://github.com/s3ql/s3ql/blob/master/rst/backends.rst#backblaze-b2), there is a different format:

`b2://<bucket-name>[/prefix]`

**Comment by estuaco** [comment]
The backend not exist in the last version of s3ql for b2 cloud, and the b2 cloud has s3 compatible api!

**Comment by powerpaul17** [comment]
Can you please try with `b2://xxx`? `xxx` should be the name of your bucket.

**Comment by diegmonti** [comment]
I'm having a similar problem with the s3c storage backend and Backblaze.

The problem seems to be related to the version of the signature.

`s3ql.backends.s3c.S3Error: InvalidRequest: The V2 signature authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256`

**Comment by Nikratio** [comment]
Indeed, the S3C backend does not support V4 authorization. For BackBlaze specifically, you should be able to use the b2 backend. Patches for V4 authorization are welcome :-).
