### ISSUE TITLE
s3ql build failed on OSX machines since 3.4.0 due to fuse3 issue

### ISSUE THREAD

**Issue by chenrui333** [s3ql/s3ql#192]
> osxfuse is still on 2.9.x API. fuse3 API is not available on macOS.

I guess there is not much we can do about in here, but just to let you know the OSX builds failed since `v3.4.0`.

---
PLEASE READ BEFORE REPORTING AN ISSUE

S3QL is a fully volunteer driven project, with only one regular active contributor (that's me). Any work that I do on S3QL has to compete with spending time with my family, doing work that I get paid for, doing something recreational without a computer, or working on S3QL features/bugs that affect me personally.

Unfortunately, this means that your issue report will most likely not get much attention from me for the foreseeable future.

Please note that this isn't meant to imply that you haven't found a real bug or came up with a great idea for a new feature - you most likely have and I'm grateful that you are taking the time to report it. But unless you have discovered a serious bug that affects a large number of users, please consider working on the issue yourself and submitting a pull request instead of a bug. I understand that not everyone has the necessary skills, but the sad fact is that just reporting the issue is not going to get it addressed either.

(I will close open issues without activity after a while, since I'm using the issue tracker to coordinate ongoing and planned work, rather than enumerate everything that could possibly be done).

**Comment by Nikratio** [comment]
Indeed, S3QL depends on libfuse 3.x. If that's not available on MacOS, that's not a bug in S3QL, sorry.
