### ISSUE TITLE
pyfuse: TypeError: an integer is required

### ISSUE THREAD

**Issue by lkuza2** [s3ql/s3ql#194]
I just recently updated s3ql to 3.5.0.  I was on 3.3.2 before this.  I use S3QL for mounting an AWS storage system and use that system with Seafile.  Have had no problems before, but after update.  Sometimes when I am performing file operations (seems to be operations happening concurrently?), S3ql crashes and attempts to unmount the drive.  If i can get more logs, please tell me how i can.  Here is the exception.

>  Uncaught top-level exception:
>  Traceback (most recent call last):
>    File "/usr/bin/mount.s3ql", line 33, in <module>
>     sys.exit(load_entry_point('s3ql==3.5.0', 'console_scripts', 'mount.s3ql')())
>    File "/usr/lib/python3.8/site-packages/s3ql/mount.py", line 131, in main
>      trio.run(main_async, options, stdout_log_handler)
>    File "/usr/lib/python3.8/site-packages/trio/_core/_run.py", line 1896, in run
>      raise runner.main_task_outcome.error
>    File "/usr/lib/python3.8/site-packages/s3ql/mount.py", line 255, in main_async
>      ret = await pyfuse3.main()
>    File "/usr/lib/python3.8/site-packages/_pyfuse3.py", line 30, in wrapper
>     await fn(*args, **kwargs)
>   File "src/pyfuse3.pyx", line 767, in main
>   File "/usr/lib/python3.8/site-packages/trio/_core/_run.py", line 741, in __aexit__
>     raise combined_error_from_nursery
>    File "/usr/lib/python3.8/site-packages/_pyfuse3.py", line 30, in wrapper
>     await fn(*args, **kwargs)
>   File "src/internal.pxi", line 253, in _session_loop
>    File "src/handlers.pxi", line 858, in fuse_create_async
> TypeError: an integer is required
>

**Comment by Nikratio** [comment]
Thanks for the report! Which pyfuse3 version are you using exactly? In the most recent version, line 858 of `src/handlers.pxi` is an `else` clause (so it cannot possibly raise a `TypeError`).

**Comment by lkuza2** [comment]
@Nikratio So in one of my dreams I responded to this Github comment (a weird dream I know), so I went under the assumption that I had taken care of this.  I just checked and realized I did not respond to this comment.  It appears the version Arch Linux has in the AUR is 2.0.0.  This most likely explains the errors I was getting as I believe you require 3.0.0 at least?  Thank you for your help.

**Comment by Nikratio** [comment]
Yes, that explains it. Thanks for reporting back.
