### ISSUE TITLE
Option to change the time before blocks get uploaded

### ISSUE THREAD

**Issue by ravenpride** [s3ql/s3ql#204]
I would like to use S3QL as backing storage for Nextcloud. When you upload big files to Nextcloud, the upload is done in a chunked way (10MB at a time). When the complete file has been uploaded, Nextcloud assembles the chunks and creates the actual file. This doubles the traffic caused by the operation. The chunks are deleted when the upload is completed. As my VPS is working rock solid, I'd like to do the entire work with the chunks in the S3QL cache - without the chunks ever reaching the S3 backend.

Would it be possible to configure the time (currently: 10s) before blocks are uploaded to the backend? Or is it a rather bad idea?

Thank you very much in advance :)

**Comment by powerpaul17** [comment]
Yes, that's something I also experience and it causes a lot of deletion requests of blocks afterwards, so very good question.. :slightly_smiling_face:

**Comment by Nikratio** [comment]
How would changing the delay until blocks are uploaded help you? You'd still have the same data  being uploaded the same way, just later.

**Comment by ravenpride** [comment]
Delaying the upload for - lets say 1 hour - would help to avoid uploding *temporary* files that get deleted within 1 hour after their creation. Some S3 providers charge for requests and/or have a minimum storage duration, so if you upload a temporary file of 1GB and delete it shortly afterwards you will be charged for several months (at Wasabi for example 3 months). And Nextcloud juggles with a lot of temporary files ;)

**Comment by Nikratio** [comment]
Ah, I see. Yeah, it should be possible to make this configurable. Pull requests welcome!

**Comment by ravenpride** [comment]
I'm happy to provide the code, please see PR #205.
