### ISSUE TITLE
"Transport endpoint not connected" after S3 service disruption

### ISSUE THREAD

**Issue by ravenpride** [s3ql/s3ql#208]
I'm running the latest S3QL version from the master branch. Yesterday evening my S3 provider Wasabi had a *service disruption*. The issue was resolved at midnight, but in the morning the mounted S3QL volume was still unaccessable and returned an "transport endpoint not connected" error. Does S3QL handle such conditions and recovers from them or is the observed behavior as expected?

The log does not contain any errors or notes that could point to the issue.

`df -h` did not list the volume. A `fsck.s3ql` aborted with a notice that the volume is still mounted, but `umount.s3ql` aborted with an error saying that the volume is *not* mounted. Only a reboot could help me out of the situation.

**Comment by powerpaul17** [comment]
Normally, S3QL should retry up to 24h (if I got that right). Unfortunately without a log or traceback it is hard to say what exactly went wrong.

If it crashed and is not accessible anymore, you have to use `fusermount -u` to release the mount point, a reboot should not be necessary, see [here](https://www.rath.org/s3ql-docs/faq.html#what-does-the-transport-endpoint-not-connected-error-mean)

**Comment by ravenpride** [comment]
Thank you for the info! Maybe I can reproduce the issue with Minio. Let's hope for the best ;)

**Comment by ravenpride** [comment]
This **could** be the issue. Please see [here](https://github.com/s3ql/s3ql/blob/00859c51929957de956c419a8d1654ceedf2956a/src/s3ql/backends/s3c.py#L159).

Error Code 521 (web server is down) could be the reason why S3QL did not retry. Wouldn't it be better to retry in the case when the server could be back within minutes or in the worst case within hours? There are short periods where Wasabi had issues in the past. To be honest, I do not exactly *know* that this *is* the issue, but we should discuss handling this error.

**Comment by ravenpride** [comment]
Is there a way to tell S3QL to log requests/responses I haven't found, yet? I would like to provide logs to track the issue down.

**Comment by d--j** [comment]
Wasabi has probably responded with a HTTP error code that that S3QL does not retry.

See https://github.com/s3ql/s3ql/blob/27d28b1508300aece803fc2868d183c2b5259892/src/s3ql/backends/s3c.py#L138 for errors that S3QL retries (e.g. HTTP status 500 will be retried, but 400 or 501 will not)

If this happens again, post the Exception that was logged in your `mount.log`

**Comment by Nikratio** [comment]
Closing per the discussion above. Please re-open if you can provide the exception traceback from `mount.log`.

While it is theoretically possible for mount.s3ql to crash without printing a traceback, this is *extremely* unlikely.
