### ISSUE TITLE
Multiple mounts with each for different storage backends (New feature Request)

### ISSUE THREAD

**Issue by samuelxhu** [s3ql/s3ql#209]
This is actually a new feature request rather than an issue...

Is it possible to support multiple fs mounts, with each for different storage backends, e.g. one from Amazon S3, another from Azure or other S3 providers. With this feature, one could easily migrate data from one storage provider to another by simply issuing a cp command. Or one can keep the data simultaneously on two storage providers for better data protection.

Thanks a lot for considering this

**Comment by d--j** [comment]
Hi @samuelxhu 

what prevents you from starting `mount.s3ql` multiple times? Each `mount.s3ql` can have its own storage backend. So what you want to do is already possible.

**Comment by samuelxhu** [comment]
Hi, Daniel,

Thanks a lot for your reply. This exactly solves my problem.

By the way, is the current S3QL version stable enough for production? I do
not want any data loss, as it risks my job.

best regards,

Sa

**Comment by d--j** [comment]
Hi @samuelxhu 

> [...] is the current S3QL version stable enough for production? [...]

It's not as battle proved as e.g. etx4 or ZFS. But for my use cases I consider S3QL stable enough.
I use S3QL for 5+ years now and never had data loss.

Since [version 3.4](https://github.com/s3ql/s3ql/blob/27d28b1508300aece803fc2868d183c2b5259892/Changes.txt#L37) S3QL had a major refactoring  and afterwards there were some more bugs but the current version is quite stable.

Read https://www.rath.org/s3ql-docs/durability.html 

PS: please move any replies over to the [mailing list](http://groups.google.com/group/s3ql).

**Comment by samuelxhu** [comment]
Dear Daniel,

Very glad to know that S3QL is stable enough for most use cases. We are
planning a project to use S3QL as an infinite storage space from S3 storage
providers for our customers, and we hope we could be able to financially
support S3QL project once the project is launched.

Given that an S3 bucket  could be nearly infinite in terms of storage
capacity, could we state  S3QL file system "Infinite" as well? OR is there
a practical limit on the storage capacity?

best regards,

Samuel

**Comment by segator** [comment]
In case help, 
I using S3QL for 4 years with a customized version that supports google drive backend,
I never lose any byte of data, but on big scale +200TB S3QL DB is to big and slow to handle, any backup freeze 3-4 minutes the FS.
Also s3ql creates 1 block per file, this is horrible slow when handling million of tiny files, even pass FSCK is horrible slow on the moment you have millions and millions of blocks.

The only 2 features I miss on S3QL to be the best Cloud FS are:
* Ideally S3QL should support 1block  per multiple tiny files, so then it will perform better for tiny files at cost of (maybe) more bandwitch and size.
* multi mount support(maybe this is possible if we can switch from a sqlite to a postgres/mariaDB?)

**Comment by samuelxhu** [comment]
Dear Isaac,

Thanks a lot for your sharing. It really helps and increases my confidence
on S3QL.

best regards,

Samuel
