### ISSUE TITLE
OSXFUSE Volume 0 (python3.8) volume name MacOS

### ISSUE THREAD

**Issue by adelorenzo** [s3ql/s3ql#221]
Hello,

First of all thank you so much for this project. It's by far IMHO the best S3 open source client. The issue I am facing is that even thought I use the --fs-name option when mounting a volume, on Finder I see **OSXFUSE Volume 0 (python3.8)**. I am doing something wrong?

The volume name works on the terminal BTW but not on Finder.

Thank you.

Regards

**Comment by Nikratio** [comment]
Thanks for the report! I'm afraid this is most likely an issue in OSXFUSE, not S3QL. I'd recommend asking there.
