### ISSUE TITLE
s3qlcp fails with ENOENT error from invalidate_inode()

### ISSUE THREAD

**Issue by nand2** [s3ql/s3ql#222]
I run S3QL v3.5.0, I do a s3qlcp, and 0.05% of the time (tens of thousands of runs), I got a filesystem crash : 

```
2020/11/13 11:14:56 [...] ERROR: Uncaught top-level exception:
Traceback (most recent call last): 
File "/data/s3ql/bin/s3qlcp", line 21, in s3ql.cp.main(sys.argv[1:]) 
File "/data/s3ql/src/s3ql/cp.py", line 93, in main ('(%d, %d)' % (fstat_s.st_ino, fstat_t.st_ino)).encode()) 
File "src/pyfuse3.pyx", line 618, in pyfuse3.setxattr 
ConnectionAbortedError: [Errno 103] Software caused connection abort: '/[..]/s3ql-mount/share/.__s3ql__ctrl__' 
```

```
2020-11-13 09:13:58.506 2420:MainThread s3ql.daemonize.detach_process_context: Daemonizing, new PID is 2421
2020-11-13 11:14:56.616 2421:MainThread s3ql.mount.unmount: Unmounting file system...
2020-11-13 11:14:56.618 2421:MainThread root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/data/s3ql/bin/mount.s3ql", line 21, in <module>
    s3ql.mount.main(sys.argv[1:])
  File "/data/s3ql/src/s3ql/mount.py", line 131, in main
    trio.run(main_async, options, stdout_log_handler)
  File "/home/manager/.local/lib/python3.6/site-packages/trio/_core/_run.py", line 1896, in run
    raise runner.main_task_outcome.error
  File "/data/s3ql/src/s3ql/mount.py", line 255, in main_async
    ret = await pyfuse3.main()
  File "/home/manager/.local/lib/python3.6/site-packages/_pyfuse3.py", line 30, in wrapper
    await fn(*args, **kwargs)
  File "src/pyfuse3.pyx", line 767, in main
  File "/home/manager/.local/lib/python3.6/site-packages/trio/_core/_run.py", line 741, in __aexit__
    raise combined_error_from_nursery
  File "/home/manager/.local/lib/python3.6/site-packages/_pyfuse3.py", line 30, in wrapper
    await fn(*args, **kwargs)
  File "src/internal.pxi", line 253, in _session_loop
  File "src/handlers.pxi", line 708, in pyfuse3.fuse_setxattr_async
  File "/data/s3ql/src/s3ql/fs.py", line 254, in setxattr
    await self.copy_tree(*tup)
  File "/data/s3ql/src/s3ql/fs.py", line 523, in copy_tree
    pyfuse3.invalidate_inode(target_inode.id)
  File "src/pyfuse3.pyx", line 834, in pyfuse3.invalidate_inode
FileNotFoundError: [Errno 2] fuse_lowlevel_notify_inval_inode returned: No such file or directory
```

So it seems s3qlcp calls fuse.setxattr which is forwarded to fs.py, to copy_tree(), and finally pyfuse3.invalidate_inode which fails. This failure goes back up and the umount is trigerred as part of the failure process.

I will try to investigate this.

**Comment by Nikratio** [comment]
Thanks for the report!

I think this might happen if the target is dropped from the kernel dentry cache while s3qlcp is running.

Could you try the following?

1. Insert a `time.sleep(120)` or something like that before the call the invalidate_inode to make sure that s3qlcp takes a while to run
2. Run s3qlcp
3. While it is running, drop the kernel caches (`echo 4 > /proc/sys/vm/drop_caches`)

Does this reproduce the problem?

**Comment by nand2** [comment]
Thank you for your debugging tip!
I was indeed able to reproduce using your steps, with droping the kernel dentry cache with `echo 2 > /proc/sys/vm/drop_caches` ( `echo 4 > /proc/sys/vm/drop_caches` did not trigger the bug).

Do you have any hints to check for the presence of the inode in kernel cache? It does not look like there is a method in pyfuse api. Or should i look at fixing it directly inside pyfuse3.invalidate_inode()?

Thanks!

**Comment by Nikratio** [comment]
That's great news, thank you for checking!

I fear that fixing this issue will be more difficult than debugging it. Being able to check if the inode is present in the kernel cache would not help - it could still be dropped in between the check and the call to `invalidate_inode`.

What this does tell us is that - at least in your case - the error message does not indicate a problem, everything is working fine (if the inode is not in the cache, there's no need to invalidate it).

I am not sure if this means that we can just suppress the error though. There may well be a different bug where everything is *not* okay that we could inadvertently hide as well.

Maybe an option is to ensure that the kernel does not drop the inode from the cache.. it might work if `s3qlcp` would `opendir` the directory before the copy. Worth testing if you are interested :-).

**Comment by nand2** [comment]
Thanks for the tip, that indeed fix the issue with os.scandir!
Here's the PR : https://github.com/s3ql/s3ql/pull/239
Do you want me to add a test? Not sure how to clear the dentry cache in an non-OS-dependent way...

**Comment by Nikratio** [comment]
I don't think there's a need to test os-independently. The bigger problem is that you need root rights to access `/proc/sys/vm`.

Nevertheless, a test would be great. I think you could model it after https://github.com/libfuse/libfuse/blob/master/test/test_examples.py#L56, i.e. skip the test unless we can write `/proc/sys/vm/drop_caches`.

Thank you for working on this!

**Comment by nand2** [comment]
And thank you for your inputs!

Ok I tried and had difficulties making a test that works now, and break before the patch.
I cannot do a test at low level such as `t3_fs_api.py::test_copy_tree_2` because the fix is in cp.py, before `pyfuse3.setxattr(.. , 'copy', ..`.
I tried at higher level like `t5_cp.py::TestCp::test`, with a trio nursery with a child clearing dentry cache in loop, hoping to catch the `await trio.lowlevel.checkpoint()` in the `copy_tree` function, but then of course there is not one single big nursery, so that didn't work out.

Here was my try : 

```
    async def test_cp_inode_invalidate(self):
        # if os.getuid() != 0:
        #     pytest.skip('drop_privileges requires root, skipping.')

        self.mkfs()
        self.mount()

        tempdir = tempfile.mkdtemp(prefix='s3ql-cp-')
        try:
            populate_dir(tempdir)

            # Rsync
            subprocess.check_call(['rsync', '-aHAX', tempdir + '/',
                                   os.path.join(self.mnt_dir, 'orig') + '/'])

            async with trio.open_nursery() as nursery:
                # clear inode cache in loop
                nursery.start_soon(self.tst_cp_inode_invalidate_clear_inode_cache)

                # Run s3qlcp
                nursery.start_soon(self.tst_cp_inode_invalidate_run_cp, nursery.cancel_scope)

        finally:
            shutil.rmtree(tempdir)

        self.umount()
        self.fsck()

    async def tst_cp_inode_invalidate_run_cp(self, cancel_scope):
        print("Copy\n")
        subprocess.check_call(self.s3ql_cmd_argv('s3qlcp') +
                              [ '--quiet', os.path.join(self.mnt_dir, 'orig'),
                                os.path.join(self.mnt_dir, 'copy')])
        cancel_scope.cancel() 

    async def tst_cp_inode_invalidate_clear_inode_cache(self):
        while True:
            print("Clear dentry cache\n")
            
            # Drop kernel dentries and inodes cache
            drop_caches = open("/proc/sys/vm/drop_caches", "w")
            drop_caches.write("2")
            drop_caches.close()

            await trio.sleep(0)
```

Do you have an hint on where to inject the dentry cache flushing to make a test?

**Comment by Nikratio** [comment]
Thanks for working on this! I would:

1. Not use `populate_dir` or `rsync` - you don't actually need any files to copy for this test, so this just distracts from what is being tested

2. Do not run s3qlcp in an async function, you can simply call `subprocess.Popen` instead of `subprocess.check_call`

3. Do not repeatedly try to clear the inode cache. Instead, monkeypatch `Operations.copy_tree` to flush the cache and then call the original implementation.

Note that the filesystem runs in a separate process, so to monkeypatch it you have to write a small wrapper that does the monkeypatching and then calls `s3ql.mount.main()`, and call this wrapper instead of the true mount.s3ql command.
