### ISSUE TITLE
Support for eu-south-1 region

### ISSUE THREAD

**Issue by jonnypa** [s3ql/s3ql#223]
Hi, I'm starting to use s3ql for bucket mount on my EC2 instances in eu-south-1 region (Milan). Mount with buckets in another region (i.e. eu-west-1) is ok but in Milan region I have an error:

`dugong.HostnameNotResolvable: Host s3-eu-south-1.amazonaws.com does not have any ip addresses`

Can you help me? Thanks

**Comment by powerpaul17** [comment]
Hello, this really looks like a name resolution problem. I think it should be `s3.eu-south-1.amazonaws.com`

**Comment by jonnypa** [comment]
Adding two lines (63,64) in `src/s3sql/backends/s3.py` now it works!

`elif self.region == 'eu-south-1':hostname = 's3.%s.amazonaws.com' % self.region`
