### ISSUE TITLE
ubuntu 21.04

### ISSUE THREAD

**Issue by adelorenzo** [s3ql/s3ql#246]
Hello,

Thank you for this project. I am having trouble with ubuntu 21.04. When I try to mount I get the following error:

```
ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/bin/mount.s3ql", line 33, in <module>
    sys.exit(load_entry_point('s3ql==3.7.0', 'console_scripts', 'mount.s3ql')())
  File "/usr/lib/s3ql/s3ql/mount.py", line 131, in main
    trio.run(main_async, options, stdout_log_handler)
  File "/usr/lib/python3/dist-packages/trio/_core/_run.py", line 1804, in run
    raise runner.main_task_outcome.error
  File "/usr/lib/s3ql/s3ql/mount.py", line 207, in main_async
    block_cache.init(options.threads)
  File "/usr/lib/s3ql/s3ql/block_cache.py", line 222, in init
    self.trio_token = trio.lowlevel.current_trio_token()
  File "/usr/lib/python3/dist-packages/trio/_deprecate.py", line 125, in __getattr__
    raise AttributeError(name)
AttributeError: lowlevel
```
This did not happen with previous versions of Ubuntu. Please let me know what I can do to fix this.

THank you very much.

**Comment by Nikratio** [comment]
Thanks for the time to report this bug! I'm afraid this looks like a problem with your Trio installation rather than with S3Ql. `trio.lowlevel` is a documented part of the trio package: https://trio.readthedocs.io/en/stable/reference-lowlevel.html

I would suggest to file this bug against the trio package that you are using.

**Comment by DoobleD** [comment]
I'm having the same issue on a fresh Ubuntu 21.04 having installed S3QL from package (a`pt-get install s3ql`).

**Comment by DoobleD** [comment]
The fix suggested [here](https://github.com/python-trio/trio/issues/1994#issuecomment-832328450) worked for me. Seems to be an Ubuntu issue.
