### ISSUE TITLE
Enhancement: Prefetching data

### ISSUE THREAD

**Issue by lorentzkim** [s3ql/s3ql#259]
Just exploring ideas. I might be able to help implement this.

I think the current behavior is when a block of data is requested, it only ever grabs that block of data. I think it might be useful to have a setting to preemptively also grab the next block(s) of data in sequence, because for some usage models the odds are pretty high that you will want the rest/more of the file.

Current behavior means there's often a small delay between copying one block and to the next, which I think amplifies if there's a larger latency.

Of course, prefetching would only make sense if the user mounted with a local cache. And if it's easy enough to determine what "next block" even is.

Is this implementable at all?

**Comment by Nikratio** [comment]
This could be implemented. I believe there was even work done on this in the past, but it was never merged (I forgot the details). Maybe you can find it in the Pull Requests.

Things to keep in mind:

- The kernel already does pre-fetching. How do we want this to interact with the internal prefetching?
- We need to think where to put the pre-fetched blocks in the LRU list. Do we consider them "just read" (i.e. they are very unlikely to be flushed when cache space runs out), or do we consider them "never accessed" (so they'd be the first to go)?

**Comment by lorentzkim** [comment]
>The kernel already does pre-fetching. How do we want this to interact with the internal prefetching?
Does that work for fuse-mounted volumes like s3ql? I thought it for block devices only e.g. `/sys/block/*/queue/read_ahead_kb` (please correct me if I'm mistaken). Is it something specified during mount? I see fuse has `max_readahead` option during mounting (I'm just looking at `mount.fuse` man page here)? Maybe it's something we can leverage?

That said, if it's something that's best controlled outside of s3ql, it's probably wisest to make it work with that rather than implementing anything clever.

>We need to think where to put the pre-fetched blocks in the LRU list. Do we consider them "just read" (i.e. they are very unlikely to be flushed when cache space runs out), or do we consider them "never accessed" (so they'd be the first to go)?
I'm leaning towards "just read" if 1) that makes it easier to implement, and 2) we're already betting we're going to read the file sequentially, and it's 3) something probably tune-able by the end user for their own use case.

**Comment by lorentzkim** [comment]
OK so it's more like `/sys/devices/virtual/bdi/*/read_ahead_kb`? For now, changing that doesn't seem to do anything for me, which is probably reasonable.

Will read through the other PR (https://github.com/s3ql/s3ql/pull/44/files) and seeing what that was about.

**Comment by Nikratio** [comment]
The kernel readahead may not be doing much because it tries to readahead so little data that it's in the same S3QL object.

**Comment by lorentzkim** [comment]
Apologies it took so long to get back to this.

After some testing, I don't think it's an s3ql thing, but more a samba thing (or a mix of the two). s3ql on its own has no trouble grabbing as much as possible as set by prefretch and whatnot, but with samba it gets weird with copying over files. Samba must be doing something weird with copy, transfer, then fetching more, with latency inbetween it all. Or could be my lacking in understanding setting up samba correctly.

Either way, not a problem anymore I think. Can close this issue.
