### ISSUE TITLE
Installing 2.28 with Python 3.7

### ISSUE THREAD

**Issue by cschlick** [s3ql/s3ql#26]
Just a comment, I was unable to get 2.28 to work using Python 3.7 without first running 
`python3 setup.py build_cython `

I am using the tar from the bitbucket site, and using amazon linux 2

**Comment by szepeviktor** [comment]
You can build s3ql with pip
https://github.com/szepeviktor/debian-server-tools/blob/master/package/s3ql-jessie.sh
or *raw-style*
https://github.com/szepeviktor/debian-server-tools/blob/master/virtualization/python-s3ql-test/Dockerfile
even not in a container.

**Comment by Nikratio** [comment]
Thanks for the report! This should fix itself with the next Cython release.
