### ISSUE TITLE
Judging effectiveness before deploying

### ISSUE THREAD

**Issue by CandyAngel** [s3ql/s3ql#265]
Heyas,

I had a look through the closed issues and couldn't see anything like this.

I'd like to try out a block-level de-duplication system but one thing I would like to see if it will be effective on the data I want to store first. I noticed in the benchmark script that the backend can be mocked.. would it be possible to pass s3ql (or a contrib script) a path and have it calculate what the equivalent `s3qlstat` output would be for that path/s3ql settings? Kind of like a "dry run" backend, perhaps where the metadata is written but the actual data blocks are not?

**Comment by Nikratio** [comment]
Possible? Sure. But someone has to write the code :-).

Unfortunately, this project does not currently have any active, regular contributors. As the maintainer, I try to review pull requests and make regular releases, but unfortunately I have no capacity to do significant development beyond that.
Issue reports that do not come with a pull request or clearly have high impact on a large number of users are therefore likely to languish.

I understand that this is frustrating for users, but I hope you can also understand that any development work that I do on this project has to compete with spending time with my family, doing work that I get paid for, doing something recreational without a computer, or working on features/bugs that affect me personally. Most bugs and ideas - unfortunately including this one - loose out in this competition.

In other words, unless you plan to work on this yourself or can recruit someone who will, it's unlikely that anyone is going to do anything about it anytime soon. Therefore, I'm closing this issue for now. Please note that this isn't meant to imply that you haven't found a real bug or worthwhile potential improvement - you most likely have and I'm grateful that you took the time to report it.
