### ISSUE TITLE
rsync changes to defunct state while copying from a s3ql to another

### ISSUE THREAD

**Issue by Miyuki0** [s3ql/s3ql#268]
I'm using rsync to copy files from a server A using s3ql to another server B, also using s3ql.
My rsync command is executed from the destination server (B) and looks like this :
`rsync -avz --progress -H -X --partial --one-file-system A:/mnt/s3ql /mnt/s3ql/test`

After a while, rsync process state changes to defunct state and command freezes.

I've tried using version 3.0.0 of s3ql but also version 3.8.1.

I'm using a cache dir of 1G and there is my mount command : 
`mount.s3ql --allow-other --cachedir=/tmp/cache --cachesize=1024000 --compress=lzma-4 --threads=3 --metadata-upload-interval=72000 local:///mnt/mfsmount /mnt/s3ql`

So far I've tried to decrease number of threads (previous was 8) and decrease cache size (previous was 8Go).

**Comment by Nikratio** [comment]
Thanks for taking the time to report this issue!

Unfortunately, this project does not currently have any active, regular contributors. As the maintainer, I try to review pull requests and make regular releases, but unfortunately I have no capacity to do significant development beyond that.
Issue reports that do not come with a pull request or clearly have high impact on a large number of users are therefore likely to languish.

I understand that this is frustrating for users, but I hope you can also understand that any development work that I do on this project has to compete with spending time with my family, doing work that I get paid for, doing something recreational without a computer, or working on features/bugs that affect me personally. Most bugs and ideas - unfortunately including this one - loose out in this competition.

In other words, unless you plan to work on this yourself or can recruit someone who will, it's unlikely that anyone is going to do anything about it anytime soon. A number of people are using S3QL with rsync, and you seem to be the only one who experiences problems.

This is just to calibrate expectations. I am grateful that you took the time and effort to report this! I'll leave this issue open for a while before closing it and who knows, maybe someone will pick it up after all :-).
