### ISSUE TITLE
contrib/expire_backups.py should warn before removing lots of backups

### ISSUE THREAD

**Issue by r0ps3c** [s3ql/s3ql#269]
When attempting to reconstruct state and clean up a set of backups taken at roughly the same time in the past, expire_backups may end up deleting all backups depending on the age ranges/cycles. For example, with the following backup directories/structures:

```
2022-03-01_10:00:00
2022-03-02_10:00:00
2022-03-03_10:00:00
2022-03-04_10:00:00
2022-03-05_10:00:00
2022-03-06_10:00:00
2022-03-07_10:00:00
2022-03-08_10:00:00
2022-03-09_10:00:00
2022-03-10_10:00:00
2022-03-11_10:00:00
2022-03-12_10:00:00
2022-03-13_10:00:00
2022-03-14_10:00:00
```

running `expire_backups.py 1 3 7 14 31` today (taken from the example in the documentation) results in:

```
...
Assuming backup interval of 1 day, 0:00:00 hours
Backup 2022-03-01_10:00:00 is 45 cycles old
Backup 2022-03-02_10:00:00 is 44 cycles old
Backup 2022-03-03_10:00:00 is 43 cycles old
Backup 2022-03-04_10:00:00 is 42 cycles old
Backup 2022-03-05_10:00:00 is 41 cycles old
Backup 2022-03-06_10:00:00 is 40 cycles old
Backup 2022-03-07_10:00:00 is 39 cycles old
Backup 2022-03-08_10:00:00 is 38 cycles old
Backup 2022-03-09_10:00:00 is 37 cycles old
Backup 2022-03-10_10:00:00 is 36 cycles old
Backup 2022-03-11_10:00:00 is 35 cycles old
Backup 2022-03-12_10:00:00 is 34 cycles old
Backup 2022-03-13_10:00:00 is 33 cycles old
Backup 2022-03-14_10:00:00 is 32 cycles old
State construction complete.
Saving reconstructed state..
Note: there is currently no backup available for age range 0 to 1
Note: there is currently no backup available for age range 1 to 3
Note: there is currently no backup available for age range 3 to 7
Note: there is currently no backup available for age range 7 to 14
Note: there is currently no backup available for age range 14 to 31
Note: there will be no backup for age range 1 to 3 in (forthcoming) cycle(s): 1
Note: there will be no backup for age range 14 to 31 in (forthcoming) cycle(s): 1-14
Note: there will be no backup for age range 3 to 7 in (forthcoming) cycle(s): 1-3
Note: there will be no backup for age range 7 to 14 in (forthcoming) cycle(s): 1-7
Backup 2022-03-04_10:00:00 is no longer needed, removing...
Backup 2022-03-01_10:00:00 is no longer needed, removing...
Backup 2022-03-08_10:00:00 is no longer needed, removing...
Backup 2022-03-02_10:00:00 is no longer needed, removing...
Backup 2022-03-06_10:00:00 is no longer needed, removing...
Backup 2022-03-13_10:00:00 is no longer needed, removing...
Backup 2022-03-09_10:00:00 is no longer needed, removing...
Backup 2022-03-12_10:00:00 is no longer needed, removing...
Backup 2022-03-07_10:00:00 is no longer needed, removing...
Backup 2022-03-10_10:00:00 is no longer needed, removing...
Backup 2022-03-11_10:00:00 is no longer needed, removing...
Backup 2022-03-03_10:00:00 is no longer needed, removing...
Backup 2022-03-14_10:00:00 is no longer needed, removing...
Backup 2022-03-05_10:00:00 is no longer needed, removing...
Saving state..
$ ls
$ 
```
i.e. all backups have been deleted.

While there are warnings in the documentation around using state reconstruction, those reference backup frequency rather than cleanup after a delay (a use case mentioned in a note earlier in the documentation), which seems to be more prone to removal of backups one would want to keep. I'd suggest either additional warnings/checks or documentation updates to avoid data loss in this situation.

**Comment by Nikratio** [comment]
Thanks for taking the time to report this issue!

Unfortunately, this project does not currently have any active, regular contributors. As the maintainer, I try to review pull requests and make regular releases, but unfortunately I have no capacity to do significant development beyond that.
Issue reports that do not come with a pull request or clearly have high impact on a large number of users are therefore likely to languish.

I understand that this is frustrating for users, but I hope you can also understand that any development work that I do on this project has to compete with spending time with my family, doing work that I get paid for, doing something recreational without a computer, or working on features/bugs that affect me personally. Most bugs and ideas - unfortunately including this one - loose out in this competition.

In other words, unless you plan to work on this yourself or can recruit someone who will, it's unlikely that anyone is going to do anything about it anytime soon.

This is just to calibrate expectations. I am grateful that you took the time and effort to report this! I'll leave this issue open to document the problem and who knows, maybe someone will pick it up after all :-).
