### ISSUE TITLE
Support using Google Cloud service account

### ISSUE THREAD

**Issue by andrewchambers** [s3ql/s3ql#28]
It would be nice if the google storage backend, when given no credentials would attempt to use the default service account. i.e. when on a google compute server, use that machines credentials.

**Comment by andrewchambers** [comment]
I don't mind adding this myself. Doing some quick research now.

**Comment by andrewchambers** [comment]
will move to bitbucket tracker.

**Comment by szepeviktor** [comment]
You can stay here, see https://bitbucket.org/nikratio/s3ql/issues/300/please-report-new-issues-on-github

**Comment by andrewchambers** [comment]
The method I'm trying to get working is with the google recommended https://google-auth.readthedocs.io/en/latest/ library. The way I imagine this working is if the password is empty and the login is oauth, then follow the typical google cloud steps outlined below, this is how most google cloud tools I have used in the past deal with credentials.

- If the environment variable GOOGLE_APPLICATION_CREDENTIALS is set to the path of a valid service account JSON private key file, then it is loaded and returned. The project ID returned is the project ID defined in the service account file if available (some older files do not contain project ID information).
- If the Google Cloud SDK is installed and has application default credentials set they are loaded and returned.
- If the application is running in the App Engine standard environment then the credentials and project ID from the App Identity Service are used.
- If the application is running in Compute Engine or the App Engine flexible environment then the credentials and project ID are obtained from the Metadata Service.

**Comment by Nikratio** [comment]
Any progress on this?

**Comment by andrewchambers** [comment]
@Nikratio Sorry I've been delayed quite severely quite with other work, though I still have a strong need for this. I also am willing to sponsor development of this if someone else is able to.

**Comment by Nikratio** [comment]
I offer paid consulting (see www.rath-consulting.biz) with a substantial discount if the work becomes open source, but I am mostly booked out. If someone wants to sponsor this I might be able to sneak this between some other work, but it's  possible that I won't get to it until after Christmas.

**Comment by Nikratio** [comment]
I'm closing this issue for now. This isn't meant to be a rejection of the idea itself, it's just that there is little point in keeping enhancement/wishlist requests in the bug tracker that no-one intends to work on. (I want to use the tracker as a tool to manage ongoing work rather than a database of possible enhancements).

**Comment by andrewchambers** [comment]
Okay, will open again if I have a pull request, for now I am using a 'hacked' branch which isn't good enough to upstream.

**Comment by Nikratio** [comment]
Re-opening since someone is sponsoring work on this.

**Comment by Nikratio** [comment]
For information about cloud service accounts, see https://cloud.google.com/docs/authentication/production

For testing, create GCE node and GS bucket, then run the python sample from https://cloud.google.com/storage/docs/reference/libraries.
Alternatively, create accounts via the google cloud user interface and download the credential json file.
