### ISSUE TITLE
Incorporate dugong module into S3QL

### ISSUE THREAD

**Issue by Nikratio** [s3ql/s3ql#312]
The Python dugong module is no longer maintained and quite complex because (1) it predates the introduction of coroutines as first class language elements (aka `async def` and `await`), (2) it tries to be framework agnostic (supporting e.g. both asyncio and trio), and (3) supports pipelining.

S3QL uses Trio and modern coroutine syntax exclusively and does not use pipelining. Turning the backends into proper coroutines (to avoid having to maintain one thread per backend connection) would require translating dugong's generator functions and generators into coroutines and awaitables. 

Most likely, it will be easier to simply integrate dugong into S3QL, drop the unnecessary features, and change it to use Trio internally. This might also make it possible to provide an asynchronous connect method.

**Comment by d--j** [comment]
Integrating a HTTP library into S3QL feels a bit out of scope of S3QL for my taste. This would probably mean the necessity to evolve it to eventually also support newer HTTP features (like HTTP2 or transfer encodings).

Might switching to https://www.python-httpx.org/ also be a possibility? This of course would mean a bigger refactoring (of all backends). But AFAIK adding coroutine/async connect support would require a refactoring anyway.

**Comment by Nikratio** [comment]
Yes, I think switching httpx would be an even better solution. I'll still go ahead with the vendoring because this is the quickest way to fix some issues now, but I'm still happy to switch to httpx in the future if someone does the work.

**Comment by Nikratio** [comment]
Fixed in commit 4f8f185 (and preceding ones).
