### ISSUE TITLE
Switch Google Storage backend to native API

### ISSUE THREAD

**Issue by andrewchambers** [s3ql/s3ql#32]
commondatastorage.googleapis.com does not seem to be an up to date endpoint as it is not listed here:

https://cloud.google.com/storage/docs/request-endpoints

Should probably update it before google turns it off at an inopportune moment.

**Comment by szepeviktor** [comment]
At least two years ago https://web.archive.org/web/20160417084517/https://cloud.google.com/storage/docs/request-endpoints

**Comment by Nikratio** [comment]
It seems the new endpoint only supports the XML and JSON APIs, but not the S3-compatible API that S3QL is using. If we want to switch to the new endpoints, we also have to implement the new API.

**Comment by andrewchambers** [comment]
@Nikratio ok, I am currently working on a project that uses s3ql and google cloud so in the upcoming weeks this will be on my agenda.

**Comment by Nikratio** [comment]
@andrewchambers Great, thanks for your help!
