### ISSUE TITLE
DatabaseChecksumError

### ISSUE THREAD

**Issue by hwertz** [s3ql/s3ql#321]
I received a s3ql.database.DatabaseChecksumError recently on a particular filesystem.  I actually retrieved a previous iteration of the DB (where checksum matched, and matched what the system thought the checksum should be on the current one too).  The only difference was a single inode with a different ctime!  I unhex'ed the name and it was "VirtualBox VMs".  

For now, I went into database.py and commented out line 539 (put a pass there) so it's just not bailing on the DatabaseChecksumError.

My strong suspicion is mount.py, a self.db.checkpoint() is run on line 682 (before the pair of async incremental uploads), but NOT line 698 (or so) just before the synchronous incremental upload where the params are also updated.  I imagine it'd be possible for stuff to end up in WAL log in the interim, and perhaps was still writing to the DB at backup time, so data written back and data when it did the checksum indeed didn't match.   The reason this would have bit me at that point is this file system is fairly inactive, so I probably did not have anything further to write back at unmount time.

I did look to see if I saw similar issues elsewhere; other uses of upload_metadata are after db.close(), except in s3qladm (upgrade part) where the upgrade upgrades the params but doesn't touch the DB, just uploads it in the new format.

I will note, in this situation (at the moment) fsck gives the DatabaseChecksumError and aborts (as does mount), and adm's tool to restore a previous DB restores a previous DB... but then fsck.s3ql does the remote metadata integrity check and bails due to the DatabaseChecksumError.

Let me know if you want further information -- I did keep a copy of the .db file where checksum matched, one where it didn't, dumped them to .sql and did a diff (that's how I found out there was only a 1-line difference), and the cache and data directories (with the actual data blocks removed, but the params files and metadata files are there in the data directory and the .db and params in the cache.)  Unfortunately, I was testing out with zstd patch so the data is zstd compressed though!  (Side note, I had some work come up but I'll have that ready in next day or two.)

Edit: Just to add, I only saw this when I had cleared out the cache directory so it was re-downloading the metadata, since in ordinary operation it uses the local db.  (And when I ran fsck.)  I don't know if VirtualBox (when it's open) constantly touches that directory or what, I have seen an issue on that same FS twice (once on one upgraded from s3ql-4.0, and once on a new s3ql fs on the same disk that I was moving the old stuff over to, to get better compression), and nothing at all on my other couple s3ql filesystems (even when I unmounted, moved the cache to a backup area, and remounted to see if it'd trigger on these other FSes when it went to download the metadata.)

**Comment by hwertz** [comment]
I just wanted to add, the single disk I've seen this on is a 4TB SMR drive, and not a well-designed one (it's one of those ones where the write buffer "hits the wall" and I/O drops from like 100MB/sec to about 1, then after a while shoots back up to 100MB/sec for a while, rinse and repeat), and I've been copying stuff around from one FS to another on there.   

In contrast to that disk doing this twice, my other 3 disks that have not had any problems, an 18TB non-SMR that'll do like 180MB/sec, and a 1TB and 5TB portable that are SMR but the firmware in them must be far better designed, instead of "hitting the wall" and having speeds drop off a cliff, they just kind of gradually have IOPS drop so under worst case it's still running at about 25% speed instead of about the 1% on that 4TB.

**Comment by hwertz** [comment]
Actually I was mistaken.. it looks like I have some other issue.  Looking at the s3ql-data, even if I throw some changes into the FS and unmount, new metadata is NOT uploading for some reason.  Like at present, I have s3ql_metadata files up through s3ql_metadata_000...fa_0064c9c430  from Aug 3 17:56 but  db Aug 4 1:32.   New params files are showing up in there though!  I'm going to run an fsck and run a  .repair and reload on the .db file first here to see what's up.

**Comment by hwertz** [comment]
OK I'm getting closer to figuring out what's going on there.  Ran a forced fsck and:
```
Uploading metadata...
Calculating metadata checksum...
ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/bin/fsck.s3ql", line 33, in <module>
    sys.exit(load_entry_point('s3ql==5.0.0', 'console_scripts', 'fsck.s3ql')())
  File "/usr/lib/s3ql/s3ql/fsck.py", line 1392, in main
    expire_objects(backend)
  File "/usr/lib/s3ql/s3ql/database.py", line 598, in expire_objects
    to_keep[blockno].add(first_le_than(candidates, seq_no))
  File "/usr/lib/s3ql/s3ql/database.py", line 555, in first_le_than
    raise ValueError('No element below %d in list of length %d' % (threshold, len(l)))
ValueError: No element below 1690944566 in list of length 1
```
So that's odd.  But definitely narrows down where to look.  I haven't actually lost any files (since I have my DB in cache still) but it'll be good to get it uploading it, that incremental upload is working great on my other drives.  (Verified in the s3ql_data that it's uploading updated metadata.)

**Comment by Nikratio** [comment]
Thanks for reporting this! This is quite concerning, I'll think about what might be happening here.

**Comment by hwertz** [comment]
OK so this is pretty odd.  I think it must be an sqlite3 bug?
My other drives (on a few different computers) are mounted at /mnt/HDD (the 1TB data drvie in the laptop, OS is on SSD), /media/user/Seagate (5TB portable), and /mnt/18TB-raw.   On the same system with the 18TB, the 4TB is in /media/user/4TB but (for consistency) I have a symlink from /mnt/4TB-raw to "../media/user/4TB". 

How odd is this -- if I mount the s3ql file system with cachedir /mnt/4TB-raw/s3ql-cache and data directory /mnt/4TB-raw/s3ql-data  the full metadata backups appear to work but incremental doesn't.   If I mount the same stuff at /media/user/4TB/s3ql-cache and /media/user/4TB/s3ql-data, no problem at all, I can unmount it and see the metadata files being updated in s3ql-data as they should be.

So, OK, rather than trying to repair things (since my DB is actually intact in cache) I can just go ahead and make a fresh s3ql filesystem, make sure to not use /mnt/4TB-raw with it, and copy things over into it.

**Comment by Nikratio** [comment]
Could you please retry with S3QL 5.1.0? There have been some related fixes, see commit 0fa77a0, commit 0fa77a0 and commit ea9d640.

**Comment by Nikratio** [comment]
I'd advise against "fixing" the issue by creating a new filesystem and copying things over. Chances are that you have found a bug that will bite you (or someone else) again in the future. So it's better to stay with the current setup until we have found a code change that fixes the issue. Being able to reproduce this is very valuable.

**Comment by hwertz** [comment]
Oh, I was running a snapshot from a few days ago, I just took a look and already have those changes in place.

**Comment by Nikratio** [comment]
Which specific commit are you testing with, then?

**Comment by Nikratio** [comment]
Could you please try whether the difference is with the data directory being a symlink or the cache directory?

Can you confirm that you are able to reproduce this issue at will (i.e., making a small change to the database and not getting a corresponding upload of a database object)?

**Comment by Nikratio** [comment]
> My strong suspicion is mount.py, a self.db.checkpoint() is run on line 682 (before the pair of async incremental uploads), but NOT line 698 (or so) just before the synchronous incremental upload where the params are also updated. 

Yes, this is a bug. Thanks for flagging this. However, I don't think this is what's causing your DatabaseChecksumError.

> I imagine it'd be possible for stuff to end up in WAL log in the interim, and perhaps was still writing to the DB at backup time, so data written back and data when it did the checksum indeed didn't match. 

This cannot happen, since all database writes happen from one thread. So while there may be data in the WAL, the database file that is uploaded cannot change between upload and checksum.

**Comment by hwertz** [comment]
Yes for sure, I'll try it now.
`total 28M
drwxrwxr-x   3 user user  68K Aug  4 04:46 .
-rw-r--r--   1 root root  347 Aug  4 04:46 s3ql_params_0064c9c460
-rw-r--r--   1 root root  347 Aug  4 04:46 s3ql_params
-rw-r--r--   1 root root  342 Aug  4 04:46 s3ql_params_0064c9c45f
-rw-r--r--   1 root root  337 Aug  4 04:45 s3ql_params_0064c9c45e
-rw-r--r--   1 root root  342 Aug  4 04:45 s3ql_params_0064c9c45d
-rw-r--r--   1 root root  335 Aug  4 04:43 s3ql_params_0064c9c45c
-rw-r--r--   1 root root  31K Aug  4 04:43 s3ql_metadata_000000000057_0064c9c45c
-rw-r--r--   1 root root  334 Aug  4 04:43 s3ql_params_0064c9c45b
-rw-r--r--   1 root root  31K Aug  4 04:43 s3ql_metadata_000000000057_0064c9c45b
-rw-r--r--   1 root root  332 Aug  4 04:43 s3ql_params_0064c9c45a
`

Yup, ...c45c is just the last one using /media/user/4TB/s3ql-cache.  I remounted (with /mnt/4TB-raw/s3ql-cache), made a file "f", unmounted, remounted (I think I did that twice just to see param file increase), then remounted and removed f, unmounted and remounted again.  No new metadata.

**Comment by hwertz** [comment]
I mean, you shouldn't have to do it ideally but if sqlite3 doesn't like paths involving a symlink, I suppose python does have os.path.realpath so the cache directory path can be canonicalized.
```
user@new-york:/media/user/4TB/s3ql-cache3$ ipython3 -i
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.31.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import os

In [2]: os.path.realpath("/media/user/4TB/s3ql-cache3/")
Out[2]: '/media/user/4TB/s3ql-cache3'

In [3]: 

```

**Comment by Nikratio** [comment]
Could you please run with `--debug-module s3ql.database` and look for the `%s opened with write-tracking` messages in both cases?

**Comment by hwertz** [comment]
> 
> This cannot happen, since all database writes happen from one thread. So while there may be data in the WAL, the database file that is uploaded cannot change between upload and checksum.

Yeah you're right, params had the correct sha256sum of the DB as stored in cache, while I was getting I suppose a stale DB out of the backend due to the incremental backups not happening.

**Comment by Nikratio** [comment]
...and could you try if the following patch fixes the issue? (Note that you need to run `build_cython` and `build_ext`):

```patch
diff --git a/src/s3ql/sqlite3ext.pyx b/src/s3ql/sqlite3ext.pyx
index 8817e6c..55444ff 100644
--- a/src/s3ql/sqlite3ext.pyx
+++ b/src/s3ql/sqlite3ext.pyx
@@ -46,7 +46,7 @@ cdef class WriteTracker:
         self.block_map.clear()
 
 def track_writes(fpath: str):
-    cdef string path_c = os.fsencode(fpath)
+    cdef string path_c = os.fsencode(os.path.realpath(fpath))
     return WriteTracker.make(&file_block_map[path_c])
 
 def set_blocksize(size: int):
```

**Comment by hwertz** [comment]
> Could you please run with `--debug-module s3ql.database` and look for the `%s opened with write-tracking` messages in both cases?
Yep.  Ain't that a B.... 
using /mnt/4TB-raw/s3ql-cache3:
```
2023-08-04 05:04:36.620 319620:MainThread s3ql.database.sqlite3_log: sqlite3: /media/user/4TB/s3ql-cache3/local:=2F=2F=2Fmedia=2Fuser=2F4TB=2Fs3ql-data3=2F.db opened with write-tracking disabled
2023-08-04 05:04:36.620 319620:MainThread s3ql.database.sqlite3_log: sqlite3: /media/user/4TB/s3ql-cache3/local:=2F=2F=2Fmedia=2Fuser=2F4TB=2Fs3ql-data3=2F.db-wal opened with write-tracking disabled
```
with /media/user/4TB/s3ql-cache3:
```
2023-08-04 05:04:53.068 319761:MainThread s3ql.database.sqlite3_log: sqlite3: /media/user/4TB/s3ql-cache3/local:=2F=2F=2Fmedia=2Fuser=2F4TB=2Fs3ql-data3=2F.db opened with write-tracking enabled
2023-08-04 05:04:53.069 319761:MainThread s3ql.database.sqlite3_log: sqlite3: /media/user/4TB/s3ql-cache3/local:=2F=2F=2Fmedia=2Fuser=2F4TB=2Fs3ql-data3=2F.db-wal opened with write-tracking disabled
```

**Comment by Nikratio** [comment]
Thanks a lot for your help, I believe we've tracked this down.

**Comment by hwertz** [comment]
Nice!  Thanks for the excellent filesystem!  There've been a few times where I worked with some large XML files (and had some games where they really don't seem to compress anything) and a few times had 1.5TB on the 1TB drive with 200GB free.  Definitely convenient!

**Comment by hwertz** [comment]
For posterity (since it seems like this worked around a bug in either sqlite3 or possibly APSW), I'll note that the sqlite3 and APSW version I'm running is 3.42.0-1, I got the Ubuntu Mantic (23.10) .deb files, since they don't have any significant dependencies they install out of the box on Ubuntu 22.04. 
Thanks!
--Henry

**Comment by Nikratio** [comment]
Sadly I have to admit that this is clear bug in S3QL, neither SQLite nor APSW is at fault.

**Comment by hwertz** [comment]
Ahh OK.  Well, it was caught early enough (good thing it does the sha256sums, one thing I appreciated on s3ql before I started using it (and continue to appreciate) is the number of failsafes it has).  And I imagine it's not too common to have a symlinked cache directory), no harm done!!

**Comment by jheredianet** [comment]
Hi, I'm worried about this. My vol was not umounted cleanly, now after fsck I'm getting this error:
` 
Starting fsck of s3c://................../
Using cached metadata.
Checking DB integrity...
Verifying consistency of most recent metadata backups:
Checking backup 0064f59058 (from 2023-09-02 02:56:15))...
Downloaded 54/54 metadata blocks (100%)
ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/local/bin/fsck.s3ql", line 33, in <module>
    sys.exit(load_entry_point('s3ql==5.1.1', 'console_scripts', 'fsck.s3ql')())
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.1-py3.10-linux-x86_64.egg/s3ql/fsck.py", line 1342, in main
    verify_metadata_snapshots(backend, count=5, include_most_recent=check_current_metadata)
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.1-py3.10-linux-x86_64.egg/s3ql/fsck.py", line 1435, in verify_metadata_snapshots
    conn = download_metadata(backend, fh.name, params)
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.1-py3.10-linux-x86_64.egg/s3ql/database.py", line 543, in download_metadata
    raise DatabaseChecksumError(db_file, params.db_md5, digest)
s3ql.database.DatabaseChecksumError: File /tmp/tmp_a6axqqn has checksum ea948b39e9c9ca8534aec423c197a88c8012e4655e15cf1b319f9e23a403848f, expected 4f7577cccce230d01110e5ed1b873a5fc89462e1cd2251663f2f8481dfde7766
`

I've tried to restore a backup with "s3qladm restore-metadata"  but no luck, it does not work with any index restored. Is there something I can do in order to fix it?
Thank in advance.

**Comment by Nikratio** [comment]
Please ask support questions on the S3QL mailing list - thanks!
