### ISSUE TITLE
Metadata backup is corrupted.

### ISSUE THREAD

**Issue by FlorentCoppint** [s3ql/s3ql#328]
Hi,

After a power outage, I'm unable to fsck my filesystem (I did it before a lot of times, successfully, after others power outages).

When I run _fsck.s3ql s3c://mys3provider/mybucket/_ I first got this error : 

`s3ql.database.DatabaseChecksumError: File /tmp/tmp64xjtk5_ has checksum 41e746bbd3be4b2f898a764f61bdc18e906ca13978f2d563b4ab811feaffbf2a, expected 922df80e826da9b66af3e9e4951d986268219571ab0666cedfbab322aa8e43a8`

I found a thread on the mailing list, and I commented in database.py the 2 lines raising this error.

Then when I re-run fsck, I now got : 

```
Starting fsck of s3c://mys3provider/mybucket/
Using cached metadata.
WARNING: sqlite3: recovered 153 frames from WAL file /home/florent/.s3ql/s3c:=2F=2Fmys3provider=2Fmybucket=2F.db-wal (SQLITE_NOTICE_RECOVER_WAL)
File system was not unmounted cleanly
Checking DB integrity...
Verifying consistency of most recent metadata backups:
Checking backup 006501ea17 (from 2023-09-28 09:19:32))...
Downloaded 372/372 metadata blocks (100%)
WARNING: sqlite3: database corruption at line 1956 of [df5c253c0b] (SQLITE_CORRUPT)
WARNING: sqlite3: database corruption at line 2106 of [df5c253c0b] (SQLITE_CORRUPT)
WARNING: sqlite3: database corruption at line 1956 of [df5c253c0b] (SQLITE_CORRUPT)
WARNING: sqlite3: database corruption at line 2106 of [df5c253c0b] (SQLITE_CORRUPT)
ERROR: *** in database main ***
Page 5401: btreeInitPage() returns error code 11
On tree page 5331 cell 444: Rowid 398393 out of order
On tree page 5331 cell 443: Rowid 398332 out of order
Page 5393: btreeInitPage() returns error code 11
On tree page 5331 cell 434: Rowid 397675 out of order
On tree page 5667 cell 72: Rowid 28987 out of order
On tree page 5626 cell 90: Rowid 8346 out of order
row 12641 missing from index sqlite_autoindex_objects_1
non-unique entry in index sqlite_autoindex_objects_1
row 20355 missing from index sqlite_autoindex_objects_1
row 147845 missing from index sqlite_autoindex_objects_1
row 147892 missing from index sqlite_autoindex_objects_1
row 147936 missing from index sqlite_autoindex_objects_1
row 148062 missing from index sqlite_autoindex_objects_1
row 148070 missing from index sqlite_autoindex_objects_1
row 148079 missing from index sqlite_autoindex_objects_1
row 148113 missing from index sqlite_autoindex_objects_1
row 148134 missing from index sqlite_autoindex_objects_1
row 148148 missing from index sqlite_autoindex_objects_1
row 148166 missing from index sqlite_autoindex_objects_1
ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/local/bin/fsck.s3ql", line 33, in <module>
    sys.exit(load_entry_point('s3ql==5.1.1', 'console_scripts', 'fsck.s3ql')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/s3ql-5.1.1-py3.11-linux-x86_64.egg/s3ql/fsck.py", line 1348, in main
    verify_metadata_snapshots(backend, count=5, include_most_recent=check_current_metadata)
  File "/usr/local/lib/python3.11/dist-packages/s3ql-5.1.1-py3.11-linux-x86_64.egg/s3ql/fsck.py", line 1445, in verify_metadata_snapshots
    raise RuntimeError(
RuntimeError: Metadata backup is corrupted. Please report this as a bug
Using 10 upload threads.
Autodetected 1048514 file descriptors available for cache entries
Enter file system encryption passphrase: ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/local/bin/mount.s3ql", line 33, in <module>
    sys.exit(load_entry_point('s3ql==5.1.1', 'console_scripts', 'mount.s3ql')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/s3ql-5.1.1-py3.11-linux-x86_64.egg/s3ql/mount.py", line 149, in main
    trio.run(main_async, options, stdout_log_handler)
  File "/usr/lib/python3/dist-packages/trio/_core/_run.py", line 2010, in run
    raise runner.main_task_outcome.error
  File "/usr/local/lib/python3.11/dist-packages/s3ql-5.1.1-py3.11-linux-x86_64.egg/s3ql/mount.py", line 188, in main_async
    backend_factory = get_backend_factory(options)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/s3ql-5.1.1-py3.11-linux-x86_64.egg/s3ql/common.py", line 282, in get_backend_factory
    fs_passphrase = getpass("Enter file system encryption passphrase: ")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/getpass.py", line 77, in unix_getpass
    passwd = _raw_input(prompt, stream, input=input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/getpass.py", line 146, in _raw_input
    line = input.readline()
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/trio/_core/_ki.py", line 191, in handler
    raise KeyboardInterrupt
KeyboardInterrupt

```

I tried to recover my metadata local db file using  
`sqlite3 "s3c:=2F=2Fmys3provider=2Fmybucket=2F.db" .recover >data.sql`
I got : 
`sql error: SQL logic error (1)`

I don't know what to do next. I don't find any thread about this issue.

What do you suggest ? :)

Thank you
Flo

**Comment by Nikratio** [comment]
Something here does not make sense. You are saying

> I'm unable to fsck my filesystem (I did it before a lot of times, successfully, after others power outages).

But also, you are getting this message:

> Verifying consistency of most recent metadata backups:
> Checking backup 006501ea17 (from 2023-09-28 09:19:32))...
> Downloaded 372/372 metadata blocks (100%)
> WARNING: sqlite3: database corruption at line 1956 of [df5c253c0b] (SQLITE_CORRUPT)
> WARNING: sqlite3: database corruption at line 2106 of [df5c253c0b] (SQLITE_CORRUPT)

In other words, the metadata backups are corrupted as well (which should have been found by the previous fsck runs). So either:

- The data got corrupted on the backend side
- You switched S3QL versions in between (older versions did not always check metadata backups)
- Your last fsck is predates the corrupted metadata backup

Could you clarify what S3QL versions you used at what times, and when you last run fsck.s3ql?

Your best bet might try find a non-corrupted metadata backup and download that using `s3qladm restore-metadata`.

**Comment by FlorentCoppint** [comment]
I always run S3QL 5.1.1, never used another version, it's a recent FS.

You say "Find a non-corrupted metadata backup" => how can I do this ? Where do I find backups and how to check if they are corrupted or not ?

**Comment by FlorentCoppint** [comment]
I did restore-metadata, I had 2 backups at the same date/time (probably during power outage) :
```
...
 25 006501ea11 2023-09-28 08:38:43
 26 006501ea12 2023-09-28 08:46:20
 27 006501ea13 2023-09-28 08:54:24
 28 006501ea14 2023-09-28 09:03:31
 29 006501ea15 2023-09-28 09:11:36
 30 006501ea16 2023-09-28 09:19:32
 31 006501ea17 2023-09-28 09:19:32
```

I tried restoring #30, #29 & #28 and I always have the same problem on fsck : 

`RuntimeError: Metadata backup is corrupted. Please report this as a bug`

I don't understand why fsck always begin to check last backup, #31 for me (006501ea17), which is obsiously corrupted... Do I have to delete it ? Manually ?

**Comment by Nikratio** [comment]
> Thank you for your answer. I always run S3QL 5.1.1, never used another version, it's a recent FS.

And when did you last run fsck.s3ql successfully? It should have identified all the faulty backups...

> I don't understand why fsck always begin to check last backup, # 31 for me (006501ea17), which is obsiously corrupted... Do I have to delete it ?

Yes. For now I'd recommend to just comment out the relevant part of the fsck.s3ql code, so you can see if the restored backup works correctly.

**Comment by FlorentCoppint** [comment]
Ok I see.

I did a restore-metadata of 006501ea16 backup.

Then I commented theses lines in fsck.py

```
#            if res[0][0] != 'ok':
#                log.error('\n'.join(x[0] for x in res))
#                raise RuntimeError(
#                    'Metadata backup is corrupted. Please report this as a bug',
#                )
```

Then I run fsck, it deleted A LOT of "spurious objects" and others that "only exists in table but not in backend".

Then I see a lot of : 
```
WARNING: Inode-block mapping for inode 28402 refers to non-existing object 378625
WARNING: File may lack data, moved to /lost+found: /lost+found/lost+found_lost+found__lost+found____lost+found________lost+found________________lost+found_____________________________ ... -1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-2-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-2-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1
```

A lot of files I recognize.

Then I mount and it seems fine. Of course last files are lost but it's OK for me.
