### ISSUE TITLE
GPL-3.0 is a deprecated SPDX license

### ISSUE THREAD

**Issue by chenrui333** [s3ql/s3ql#331]
👋 GPL-3.0 is deprecated by [SPDX](https://spdx.org/licenses/GPL-3.0), please consider using [GPL-3.0-only](https://spdx.org/licenses/GPL-3.0-only) or [GPL-3.0-or-later](https://spdx.org/licenses/GPL-3.0-or-later). Thanks!

**Comment by Nikratio** [comment]
Thanks for the report! I'm afraid I don't completely understand what you mean. Would you be able to submit a pull request that illustrates what you think needs changing?

**Comment by chenrui333** [comment]
Yeah, totally.

**Comment by Nikratio** [comment]
Will close this issue for now, happy to review the pull request when it's ready.
