### ISSUE TITLE
Bandwidth Alliance support for Backblaze

### ISSUE THREAD

**Issue by gymnae** [s3ql/s3ql#333]
Since Backblaze cooperates with the Bandwidth alliance, most notably Cloudflare, it's possible to [avoid egress](https://www.backblaze.com/cloud-storage/solutions/cdn) fees when routing downloads through a CDN partner.

rclone supports this feature, I was wondering if there's a way to use this feature also in s3ql.

**Comment by d--j** [comment]
Hello @gymnae 

could you please elaborate on what you want S3QL to do? Do you want S3QL to be able to run on Cloudflare's edge network? Do you want S3QL to be able use some kind of proxy?

> rclone supports this feature, I was wondering if there's a way to use this feature also in s3ql.

Please provide a link to documentation. A quick internet search did not provided any results on how rclone would benefit from the bandwidth alliance.

**Comment by gymnae** [comment]
Hi @d--j,

rclone adjust download URLs on the fly and doesn't pull directly from buckets, but via a provided CDN URL. Thus, all downloads to either the cache on the rclone host or from clients requesting data via rclone from Backblaze is arriving via CDN. rclone does not need to run on Cloudflare's edge for this to work, but it's a combination of Cloudflare workers and a configuration setting for rclone.

rclone benefits from the CDN integration via workers:

https://rclone.org/b2/#standard-options
>  --b2-download-url
> Custom endpoint for downloads.
> 
> This is usually set to a Cloudflare CDN URL as Backblaze offers free egress for data downloaded through the Cloudflare network. Rclone works with private buckets by sending an "Authorization" header. If the custom endpoint rewrites the requests for authentication, e.g., in Cloudflare Workers, this header needs to be handled properly. Leave blank if you want to use the endpoint provided by Backblaze.
> 
> The URL provided here SHOULD have the protocol and SHOULD NOT have a trailing slash or specify the /file/bucket subpath as rclone will request files with "{download_url}/file/{bucket_name}/{path}".

Here docu from backblaze for CDN integration in general:
https://www.backblaze.com/docs/cloud-storage-deliver-private-backblaze-b2-content-through-cloudflare-cdn

Finally, the worker template for Cloudflare and Backblaze
https://github.com/backblaze-b2-samples/cloudflare-b2

**Comment by d--j** [comment]
Hi @gymnae ,
thanks for the clarifications. 

Could you test PR #334? It should implement support for this. If the Cloudflare Worker indeed does not send the `Content-Size` header (as https://github.com/rclone/rclone/blob/master/backend/b2/b2.go#L1831-L1837 states),  you might need to also patch/fix the Cloudflare worker since we do rely on the header to be present (and cannot circumvent it the way rclone did there).

**Comment by gymnae** [comment]
Hi there,
I’m currently moving away from B2 again, since the costs were higher than anticipated. Back to good old HDDs.
Thanks for your work, I’ll close this issue.
