### ISSUE TITLE
Swift backend depends on packaging module

### ISSUE THREAD

**Issue by szepeviktor** [s3ql/s3ql#346]
Swift backend depends on packaging module but it is not a dependency.

https://github.com/s3ql/s3ql/blob/94b9951b88662bfa7e0dfa22ff1d256dcf5ab900/src/s3ql/backends/swift.py#L26

https://pypi.org/project/packaging/

**Comment by d--j** [comment]
I thought that it is vendored in [setuptools](https://github.com/pypa/setuptools/blob/main/pkg_resources/_vendor/vendored.txt) and as such is available anyway. If that's a wrong assumption we might change the one version compare to something simpler (like converting the version string to float) and drop this requirement.

**Comment by szepeviktor** [comment]
I use `PYTHONPATH="/opt/s3ql/lib/python3.9/site-packages"` to install s3ql in a separate directory
and `pip3 install --ignore-installed ...` ignores system packages.

It would be very nice not to use `packaging`.

**Comment by d--j** [comment]
As it turns out, we can just get rid of the whole version check alltogether. It was used to detect a special server side copy feature that we do not use anymore.

**Comment by szepeviktor** [comment]
Thank you.
