### ISSUE TITLE
Signed S3 requests

### ISSUE THREAD

**Issue by szepeviktor** [s3ql/s3ql#347]
Do you plan to send signed requests in s3/s3c?

https://github.com/s3ql/s3ql/blob/94b9951b88662bfa7e0dfa22ff1d256dcf5ab900/src/s3ql/backends/s3.py#L164-L165

https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html

**Comment by szepeviktor** [comment]
Related to S3 API versions: https://github.com/s3ql/s3ql/issues/164#issuecomment-624260897

**Comment by Nikratio** [comment]
No current plans, no. Is there a compelling reason to do so?

**Comment by szepeviktor** [comment]
Compelling for UpCloud users only. UpCloud's S3-compatible object storage need signed requests.

**Comment by xeji** [comment]
@szepeviktor thanks for asking but I have no plans nor the time to implement this in the near future.

**Comment by szepeviktor** [comment]
It turns out that the problem with UpCloud was **not** message signing but signature version.
v5.2.0 includes V4 signature support that make UpCloud Object Storage work!
https://github.com/s3ql/s3ql/releases/tag/s3ql-5.2.0
Thank you,
