### ISSUE TITLE
Option for automatically check fs when recommended

### ISSUE THREAD

**Issue by szepeviktor** [s3ql/s3ql#36]
>  WARNING: Last file system check was more than 1 month ago, running fsck.s3ql is recommended.

It would be nice to have an option **in fsck.s3ql** that would actually check the fs instead of this warning.

I run fsck.s3ql right before mount.s3ql

Thanks.

**Comment by Nikratio** [comment]
Thanks for the report! I don't quite understand though, the above message is only printed by `mount.s3ql`, not `fsck.s3ql`. `fsck.s3ql` will indeed check the file system, without printing a warning.

**Comment by szepeviktor** [comment]
@Nikratio Thank you!
So [using both](https://github.com/szepeviktor/debian-server-tools/blob/master/backup/system-backup.sh#L279-L283) **automatically** does testing.
