### ISSUE TITLE
Installation Issue on Ubuntu 22

### ISSUE THREAD

**Issue by umardraz** [s3ql/s3ql#364]
Hello

I need a help that how to install this s3ql on ubuntu 22, I had followed the following installation instruction but I think there is some issue in the installation

https://www.rath.org/s3ql-docs/installation.html#installing-s3ql

I trying to build for a **current user**, all the steps was ok but the following command failed with this error

```
test:~/s3ql# ~/.local/lib/s3ql-venv/bin/python3 setup.py build_ext --inplace
MANIFEST.in exists, running in developer mode
running build_ext
building 's3ql.sqlite3ext' extension
x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/root/.local/lib/s3ql-venv/include -I/usr/include/python3.10 -c src/s3ql/sqlite3ext.cpp -o build/temp.linux-x86_64-3.10/src/s3ql/sqlite3ext.o -Wall -Wextra -Wconversion -Wsign-compare -Werror -Werror=conversion -Werror=sign-compare -Wno-unused-parameter -Wno-unused-function
cc1plus: fatal error: src/s3ql/sqlite3ext.cpp: No such file or directory
compilation terminated.
error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
```

Would you please help me that what is correct and easy way to install this utility

**Comment by d--j** [comment]
You did not follow the install instructions.

Looks like you tried to install from a GIT checkout or a ZIP from Github ("MANIFEST.in exists, running in developer mode"). There you need to generate the .cpp file yourself (with Cython – `python setup.py build_cython`).

Just follow the install instructions and use a release tarball ( https://github.com/s3ql/s3ql/releases/download/s3ql-5.2.1/s3ql-5.2.1.tar.gz ) instead of the source you are using right now.

**Comment by umardraz** [comment]
HI d--j thanks for your response, would you please help me how I can mount my s3 storage

I am using **AWS_ACCESS_KEY** and Secret to access my AWS resourses. I have tried this

/root/.s3ql/authinfo2
```
[s3]
storage-url: s3://
backend-login: xxxxxxx
backend-password: xxxxxxx
```

python3 bin/mkfs.s3ql s3://xxxx/s3ql

the following command failed with this error

**s3ql.http.HostnameNotResolvable: Host s3.xxx.amazonaws.com does not have any ip addresses**

the bucket location is **us-east-1**

**Comment by d--j** [comment]
replyed on mailing list https://groups.google.com/g/s3ql/c/jZ_vHOr-Bbg
