### ISSUE TITLE
s3qlctrl: error: argument <action>: invalid choice: 'upload-meta'

### ISSUE THREAD

**Issue by drgrumpy** [s3ql/s3ql#371]
Using version 5.2.2

According to the manual 'Tips and Tricks' section:

> Call [s3qlctrl backup-metadata](http://www.rath.org/s3ql-docs/special.html#s3qlctrl) right after a every backup to make sure that the newest metadata is stored safely.

But when I call s3qlctrl backup-metadata I get the error:
s3qlctrl: error: argument <action>: invalid choice: 'upload-meta'

I guess this means the 'upload-meta' has been deprecated, as it is not listed in the actions for s3qlctrl, does this mean that it is no longer necessary or should I do something else like flush-cache ?

**Comment by d--j** [comment]
The action is called `backup-metadata` and not `upload-meta`. It was called `upload-meta` prior to version 5.0.0 of S3QL.

The command line is:
```shell
s3qlctrl backup-metadata /path/to/mount-point
```

**Comment by drgrumpy** [comment]
Thanks, must read more carefully in future.
