### ISSUE TITLE
Make s3qlrm more resilient

### ISSUE THREAD

**Issue by Nikratio** [s3ql/s3ql#39]
I think there may be issues when we create (or modify) data in a directory while it is being removed by s3qlrm. We need to look into that.

**Comment by szepeviktor** [comment]
> we create (or modify) data in a directory while it is being removed by s3qlrm

How is that possible at the same time?
Can two clients mount the same s3qlfs?

**Comment by Nikratio** [comment]
Like this, for example:

```
# s3qlrm foo &
# echo whatever > foo/bar/dir/somefile
```

**Comment by szepeviktor** [comment]
Thank you.

**Comment by macropin** [comment]
Is there any notion of mutex / locks when performing these operations? Ideally all dangerous operations should block. Similarly a lock could be used to prevent concurrent bucket mounts which would otherwise lead to corruption.

**Comment by Nikratio** [comment]
There is no way to do locking, because different instances do not know about each other and cannot directly communicate.

**Comment by macropin** [comment]
What about writing a `LOCK` file to the bucket with the client details on mount? The `LOCK` would be removed on a clean unmount. Cleanup would require a `--force` or manual removal of the lock file.

**Comment by Nikratio** [comment]
This is roughly what S3QL already does, but it is not a lock because you cannot atomically check for existence and create the file, so it's always possible that two instances both find that the lock file doesn't exist, and then both create it.

**Comment by Nikratio** [comment]
Looking at the code, I believe this case should actually be handled correctly. I've also tried reproducing this in practice (by slowing down `remove_tree()` artifically), and it seems to work just fine:

```
nikratio@vostro ~/t/mnt> md t1; touch t1/file
nikratio@vostro ~/t/mnt> s3qlrm t1 &; sleep 1; touch t1/file2
processing directory with inode 49
has 1 sub-entries
nikratio@vostro ~/t/mnt> attempting to delete entry  b'file' 50
regular file, removing
removing root (49)
ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "/home/nikratio/in-progress/s3ql/bin/s3qlrm", line 21, in <module>
    s3ql.remove.main(sys.argv[1:])
  File "/home/nikratio/in-progress/s3ql/src/s3ql/remove.py", line 72, in main
    pyfuse3.setxattr(ctrlfile, 'rmtree', cmd)
  File "src/pyfuse3.pyx", line 629, in pyfuse3.setxattr
OSError: [Errno 39] Directory not empty: 't1/.__s3ql__ctrl__'
```
