### ISSUE TITLE
S3QL shouldn't crash when attempting to open incompatible version of file system

### ISSUE THREAD

**Issue by SCDealy** [s3ql/s3ql#42]
Okay, maybe this time I have it right :-) When attempting to mount a version of the S3QL file system which is incompatible with the current software, S3QL should report that fact and exit gracefully rather than throwing an exception. I see a two possible senarios for the error message: older software/newer file system (software upgrade required), newer software/older file system (software downgrade or file system upgrade required).

An example of the problem. Using S3QL version 2.21 and attempting to mount a file system from version 2.11.2 gives the following result:

mount.s3ql --cachedir cache local://Test-i686-32bit mnt
Using 10 upload threads.
Autodetected 1048514 file descriptors available for cache entries
ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/bin/mount.s3ql", line 11, in <module>
    load_entry_point('s3ql==2.21', 'console_scripts', 'mount.s3ql')()
  File "/usr/lib/s3ql/s3ql/mount.py", line 129, in main
    (param, db) = get_metadata(backend, cachepath)
  File "/usr/lib/s3ql/s3ql/mount.py", line 374, in get_metadata
    param = backend.lookup('s3ql_metadata')
  File "/usr/lib/s3ql/s3ql/backends/comprenc.py", line 74, in lookup
    meta_raw = self.backend.lookup(key)
  File "/usr/lib/s3ql/s3ql/backends/local.py", line 66, in lookup
    return _read_meta(src)
  File "/usr/lib/s3ql/s3ql/backends/local.py", line 254, in _read_meta
    raise CorruptedObjectError('Invalid object header: %r' % buf)
s3ql.backends.common.CorruptedObjectError: Invalid object header: b'\x80\x02}q\x00(X\x0e\x00'

**Comment by Nikratio** [comment]
Thanks for the report! Yes, this is a known issue. In most cases, S3QL does print the right error message. However, for some version jumps the extra code that would have been necessary to distinguish corrupted data from prior version data would have imposed too much of a maintenance burden. You have unfortunately hit one of those cases..
