### ISSUE TITLE
Support concurrent read-only mounts

### ISSUE THREAD

**Issue by awenny** [s3ql/s3ql#46]
While s3ql file systems can be mounted only once at a time, it would be great if the file systems could be mounted read-only multiple times while it is mounted somewhere else in write mode.
While having only one mount which can change the file system, plenty others could read the data and see newer changes almost immediately. "s3qlctrl" can be used to fetch the latest metadata where it is mounted read-only.
For me, a write once/read many scenario would be a great enhancement.
Thanks

**Comment by Nikratio** [comment]
This is a great idea, thanks for taking the time to suggest it! Do you think you could work on this (or do you know someone who could)?

S3QL is a fully volunteer driven project[1]. This means that new features and bugfixes are implemented only when someone has a personal interest in them and therefore also does the necessary
work. Suggestions for new features that are just submitted to the issue tracker are therefore unlikely to result in the feature being implemented - as great as the feature might be. 

So if someone (that probably means you) is interested in working on this, then I'd be happy to give guidance and review patches. If not, I'm afraid this suggestion will just languish on the issue tracker.  

[1] Actually, that's not strictly true. I do offer paid consulting with discounts for code that makes it into the official S3QL release. Contact me privately if that's something you'd be interested in.

**Comment by awenny** [comment]
I'm happy, you like this feature, and I'd generally be interested in working on it. But I'm afraid I'm not experienced enough in coding with Python on that degree. It's more an extended shell usage for me. Maybe with you're or someone else's help, it would be possible.
I'll start off with walking through the source code.
