### ISSUE TITLE
systemd readyness notification is not working

### ISSUE THREAD

**Issue by Nikratio** [s3ql/s3ql#57]
[migrated from BitBucket]

I have the same issue.

Job for s3ql-mountpoint-storage.service failed because the service did not take the steps required by its unit configuration.

journalctl -xe shows

```
Nov 01 20:37:02 peschue1 systemd[1]: s3ql-mountpoint-storage.service: Failed with result 'protocol'.
Nov 01 20:37:02 peschue1 systemd[1]: Failed to start S3QL mount 'storage'.
-- Subject: Unit s3ql-mountpoint-storage.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit s3ql-mountpoint-storage.service has failed.
-- 
-- The result is RESULT.
```

"mount" still shows the mount, but trying to use the filesystem shows

```
$ ls /mnt/s3ql/storage
ls: cannot access '/mnt/s3ql/storage': Transport endpoint is not connected
```

Systemd knows that the mount was not successful so I cannot use "systemctl stop <service>" to unmount cleanly.

The mount.log shows

```
2018-11-01 20:37:02.128 12208:MainThread s3ql.mount.main: Setting cache size to 7886 MB
2018-11-01 20:37:02.129 12208:MainThread s3ql.block_cache.__init__: Initializing
2018-11-01 20:37:02.132 12208:MainThread s3ql.mount.main: Mounting s3://eu-west-1/XXXX/ at /mnt/s3ql/storage...
```

`systemctl status s3ql-mountpoint-storage`

shows

```
● s3ql-mountpoint-storage.service - S3QL mount 'storage'
   Loaded: loaded (/etc/systemd/system/s3ql-mountpoint-storage.service; enabled; vendor preset: enabled)
   Active: failed (Result: protocol) since Thu 2018-11-01 20:37:02 CET; 2min 1s ago
  Process: 12208 ExecStart=/usr/bin/mount.s3ql --debug --allow-other --threads=1 --max-cache-entries=5 --compress=zlib s3://eu-west-1/XXXX
 Main PID: 12208 (code=exited, status=0/SUCCESS)
```

Interestingly, "umount /mnt/s3ql/storage" exits with no error and trying to fsck the seemingly crashed volume terminates with an exception

```
Starting fsck of s3://eu-west-1/XXXX/
Using cached metadata.
ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/bin/fsck.s3ql", line 11, in <module>
    load_entry_point('s3ql==2.26', 'console_scripts', 'fsck.s3ql')()
  File "/usr/lib/s3ql/s3ql/fsck.py", line 1212, in main
    assert not os.path.exists(cachepath + '-cache') or param['needs_fsck']
```

mounting the same thing manually afterwards works nicely, so it actually did not crash or mark it as dirty

EDIT: with --fg and Type=notify it works nicely (unless I use the filesystem while doing systemctl stop ... then systemd immediately terminates the mount.s3ql process and does not cleanly unmount because umount.s3ql did not wait but display an error message)

**Comment by peschue** [comment]
Thank you!
