### ISSUE TITLE
Reconsider consistency handling

### ISSUE THREAD

**Issue by Nikratio** [s3ql/s3ql#60]
Both Google Storage and Amazon S3 these days offer strong global consistency for writes of new objects. We should check if it's worth making this assumption for every backend in S3QL to simplify the code. 

For data objects, we always create new objects and should thus be safe. For metadata, we could include the sequence number in the object name (and upload a dummy object as a dirty flag). It's not yet clear to me how we can do a race-free removal of old metadata objects though.

(I believe consistency guarantees for Swift and other S3 compatible services are typically not documented at all or strong and "global" just by virtue of being small-scale, so it seems safe to base the decision on what Google and AWS provide)

**Comment by Nikratio** [comment]
Idea:

- Switch to age based metadata backup expiration
- Require only immediate, global read after create consistency
- Include sequence number in metadata object name, get rid of separate marker object
- Make the metadata expiration age configurable, and instruct users that it must be longer than the maximum time it may take for newly created objects to show up in the object listing
- When retrieving metadata, read forward from the index indicated in the object list

Advantages:
- We no longer need to rotate metadata objects
- Instructions for handling eventual consistency become easier to understand
- We no longer have to maintain a marker object

**Comment by Nikratio** [comment]
This probably needs a bump of the file system revision.

For old versions to display the correct error, we need to leave behind a dummy `s3ql_metadata` file and one matching `s3ql_seq_no` with the increased revision number.

For newer clients to detect old filesystems, we can simply fall back to looking for an `s3ql_metadata` object if no numbered metadata object exists.

**Comment by d--j** [comment]
How exactly will the age base expiration work? Don't we introduce a necessity for all clients to have (more or less) synced clocks with that?
