### ISSUE TITLE
Migrate away from pycrypto

### ISSUE THREAD

**Issue by pelag0s** [s3ql/s3ql#65]
The pycrypto library [has not seen any updates since 2014](https://github.com/dlitz/pycrypto) and [is essentially dead](https://github.com/dlitz/pycrypto/issues/238). It might even contain [unpatched security issues](https://github.com/benkonrath/transip-api/pull/34) now.

There are also problems with the s3ql installation correlated to pycrypto, e.g. [on Arch Linux](https://aur.archlinux.org/packages/s3ql/) (see comments).

People suggest moving to [cryptography](https://github.com/benkonrath/transip-api/pull/34) or [PyCryptodome](https://github.com/dlitz/pycrypto/issues/238) instead.

**Comment by szepeviktor** [comment]
Very nice.
Thank you.

**Comment by djmaze** [comment]
Awesome, that was fast.. Thank you!
