### ISSUE TITLE
guidance needed - 10TB in selfhosted distributed filesystem

### ISSUE THREAD

**Issue by eleaner** [s3ql/s3ql#66]
Hi, need some advice

I store more than 10TB photos in S3QL on a self hosted distributed filesystem.
Technically it is LizardFS, so S3QL does not talk to it natively but when mounted locally its POSIX compliant.

I wonder what is the best approach for the fastest backups.
Option 1. I mount LizardFS locally and setup S3QL local:// 
Option2. I mount LizardFS on one of my remote servers and expose via minio and then do S3QL s3://
Option3. like Option2 but I do S3QL local:// on my remote server and expose S3QL filesystem via minio.

What are the main differences between the three approaches - speed wise?
We are talking home broadband around 10mbps so everything will be slow but maybe one will be less slow?

I assume Option3 will push the most data through since deduplication happens remotely, something like rclone could help here but I think it still will be the slowest.

I believe the choice is between local vs S3/minio 

What are your opinions?

**Comment by segator** [comment]
Umh I think best options is 2. you will use S3 API so it's pretty standard in a future you want to migrate to  cloud service or other local s3 solutions, like ceph, minio, edgefs and so on.
It will be easier,
Anyway I dont like the idea to install services like minio over other mountpoint, minio itself handle distributed object storage and replication/erasure coding, so you dont need lizardFS, in case you want anyway FS you can check ceph that have block, File and, Object(s3 and swift)
and some guys are working in a new distributed Object storage called edgeFS very simple and powerfull and does eventual consistency that works on high latency systems(multi-cloud FS for example)

**Comment by eleaner** [comment]
it's a SOHO setup I try to manage in my limited spare time,
Multiple data centres and erasure coding 4.2 for resiliency (and price).

Ceph is way more complex and as far as I remember does erasure coding in
one datacenter only. Other than that only replication.
EdgeFS requires kubernetes (I gave up on setup due to complexity, forget to
manage this) and I think it does not do erasure.
Minio would be an option but I cannot easily add disk space, and I am not
prepared to pay in advance for too much.

Lizard is not perfect by any means, but it's a trade-off.

Would use of Option 2 (S3 api) have a speed benefit over going local://
technically it's one layer more but maybe S3QL handles S3 backend somehow
different/better?

Marcin

**Comment by segator** [comment]
>Multiple data centres and erasure coding 4.2 for resiliency (and price).
Does LizardFS works stable on high latency scenarios over internet? (Multi-Cloud)
I supose it does eventual consistency if works stable.
I actually looking for a  replicated/distributed FS that allows multi-cloud (high latency), I wanted to go for edgefs but it's too early to use it.

Ceph as you said, is for low latency environments(LAN)
EdgeFS works without kubernetes(Rook), check their documentation, I installed it only with docker containers.

I think S3QL writes object metadata in the header of the written object when using local:// so when s3ql head a object or need to fsck  actually need to open the file, for S3 Metadata is written separately of the object. @Nikratio can give us more info about this.

**Comment by eleaner** [comment]
EdgeFS in containers is a power-tip, thank you

A few more question about that
1. does it do native S3?
2. does it to erasure coding or only replication?

**Comment by Nikratio** [comment]
Thanks for your interest in S3QL! As far as I can tell, this is a question about how to use/install S3QL. Could you please send it to the S3QL mailing list instead? 

I'd like to reserve use of the issue tracker for actual bugs in S3QL rather than general user support.  To subscribe to the list, send an email to `s3ql+subscribe@googlegroups.com`. After that you can post your question by sending it to `s3ql@googlegroups.com`. Alternatively, you can subscribe and access the list online at https://groups.google.com/d/forum/s3ql.

Thanks!
