### ISSUE TITLE
backend-options cannot be specified in authfile

### ISSUE THREAD

**Issue by eleaner** [s3ql/s3ql#68]
Hi

is it possible that tcp-timeout option is ignored with s3c backend?
regardless of what I set my error is the same
e.g. fsck.s3ql  --backend-options tcp-timeout=2000 .....

> ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/bin/fsck.s3ql", line 11, in <module>
    load_entry_point('s3ql==2.33', 'console_scripts', 'fsck.s3ql')()
  File "/usr/lib/python3.6/site-packages/s3ql-2.33-py3.6-linux-x86_64.egg/s3ql/fsck.py", line 1133, in main
    backend = get_backend(options)
  File "/usr/lib/python3.6/site-packages/s3ql-2.33-py3.6-linux-x86_64.egg/s3ql/common.py", line 248, in get_backend
    return get_backend_factory(options)()
  File "/usr/lib/python3.6/site-packages/s3ql-2.33-py3.6-linux-x86_64.egg/s3ql/common.py", line 260, in get_backend_factory
    backend = options.backend_class(options)
  File "/usr/lib/python3.6/site-packages/s3ql-2.33-py3.6-linux-x86_64.egg/s3ql/backends/s3c.py", line 81, in __init__
    self.conn = self._get_conn()
  File "/usr/lib/python3.6/site-packages/s3ql-2.33-py3.6-linux-x86_64.egg/s3ql/backends/s3c.py", line 131, in _get_conn
    conn.timeout = int(self.options.get('tcp-timeout', 20))
AttributeError: 'str' object has no attribute 'get'

S3QL 2.33
compiled under alpine
Python 3.6.6

**Comment by Nikratio** [comment]
Thanks for the report! Could you give me an example command line to reproduce the issue? The following works fine (apart from the fact that I don't have an S3 server running on localhost):

```
$ bin/fsck.s3ql --version
S3QL 2.33
$ bin/fsck.s3ql --backend-options tcp-timeout=20 s3c://localhost/bar
Enter backend login:  <foo>
Enter backend password: <bar>
Encountered ConnectionRefusedError ([Errno 111] Connection refused), retrying Backend.open_read (attempt 3)...
Encountered ConnectionRefusedError ([Errno 111] Connection refused), retrying Backend.open_read (attempt 4)...
[...]
```

**Comment by eleaner** [comment]
I was using the authinfo file and other than that tried to play with the
length of tcp-timeout but it was always failing

**Comment by eleaner** [comment]
and I guess the response of my s3c server was not as fast as expected

**Comment by Nikratio** [comment]
so.. can you give me an example command line and authinfo2 file (just XX-out your credentials) that reproduces the problem? Without that I'm afraid there isn't much I can do.

**Comment by eleaner** [comment]
Sure
give me a moment, I will have to recreate it

**Comment by eleaner** [comment]
I hope this helps

fsck.s3ql s3c://192.168.1.21:9000/default

/ # cat /root/.s3ql/authinfo2
[fs]
storage-url: s3c://192.168.1.21:9000/default
backend-login: XXX
backend-password: XXX
backend-options: no-ssl tcp-timeout=200
fs-passphrase: XXX

curl http://192.168.1.21:9000
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access
Denied.</Message><Resource>/</Resource><RequestId>157972BFA7F23BD9</RequestId><HostId>3L137</HostId></Error>/
#

the backend is minio on local network without SSL
bucket "default" is just a leftover from some earlier testing

**Comment by eleaner** [comment]
@Nikratio 
so assuming I do not have backend-options in authinfo, what should be my command line?

fsck.s3ql --backend-options 'no-ssl, tcp-timeout=200' s3c://192.168.1.21:9000/default 
is failing on "Unknown backend option:  tcp-timeout"

**Comment by Nikratio** [comment]
Mind the space

**Comment by eleaner** [comment]
thank you

**Comment by cavasinf** [comment]
@Nikratio I've a problem related with this feature.

In my case I just want to pass the `domain` param to `backend-options`.
Here's the command:
```bash
sudo mkfs.s3ql --backend-options domain=default --authfile s3qlcredentials.txt swiftks://auth.cloud.ovh.net/$REGION_NAME:$CT_NAME
```

But the result told me that there is an invalid option which is `blank` (or empty/null/...).
Result response : 
```bash
Unknown backend option: domaindebian@daemon1:~$
```
Note: See the `domaindebian@daemon1` that comming back after the response, I think the error return an unescaped character.. which is screwing up the console display.

Any idea what the problem is ?
