### ISSUE TITLE
Allow google storage access in the presence of bucket 403 errors.

### ISSUE THREAD

**Issue by andrewchambers** [s3ql/s3ql#72]
Currently I have service accounts who do not have bucket listing permissions, but do have access to bucket objects if they know the randomly generated bucket name. In this case I get a 403 error, which can be safely ignored and mounting would proceed.

This bucket request https://github.com/s3ql/s3ql/blob/8f9aa76a41b63d03c4e702771957eb0efcd0884a/src/s3ql/backends/gs.py#L134 causes mounting to fail in a situation where it does not need to.

I'm happy for this to be a backend option (skip bucket check?), or perhaps I can keep it as a private patch. It might be a rare enough requirement that It doesn't make sense to be in the code, but I would like your opinion.

**Comment by Nikratio** [comment]
S3QL does need listing permissions to determine the name of the most recent `s3ql_seq_no` object (and probably in a few other cases). Are you sure the above change is sufficient to make S3QL work without listing privileges? Also, fsck absolutely needs to be able to list bucket contents at the moment.

**Comment by andrewchambers** [comment]
@Nikratio  I meant bucket query permissions, not object query. So they have permission to list objects within a bucket, but not permission to query whether a bucket exists.

Just to clarify further, in google cloud roles I have given my service account these permissions:
```
storage.objects.create
storage.objects.delete
storage.objects.get
storage.objects.list
storage.objects.update
```

But not these permissions:

```
storage.buckets.get
storage.buckets.list
storage.buckets.create
storage.buckets.delete
```

**Comment by andrewchambers** [comment]
This patch is enough to fix the issue on my own branch.

https://github.com/andrewchambers/s3ql/commit/9f76975cbe40f5ea59a2820a78fdb3d5a477a842

**Comment by Nikratio** [comment]
I think the advantages of failing early and with a clear error message if the bucket does not exist weigh heavier than the ability to limit S3QL from getting bucket informations - the latter seems to be a comparatively harmless since only read access is involved. So I think I'll keep this as-is. Thanks for reporting though!
