### ISSUE TITLE
Don't depend on `ps` supporting `-p`

### ISSUE THREAD

**Issue by stjosh** [s3ql/s3ql#75]
Hi @Nikratio 

First of all, many thanks for this incredibly useful project! I'm currently doing some experiments running s3ql on Alpine Linux / BusyBox. Basically, this seems to work just fine, but there's one little caveat: `umount.s3ql` is relying on [calling `ps -p`](https://github.com/s3ql/s3ql/blob/master/src/s3ql/umount.py#L94), which is [not supported in the BusyBox `ps` implementation](https://busybox.net/downloads/BusyBox.html#ps). Since this does not work and `umount.s3ql` then [just assumes that the daemon has stopped](https://github.com/s3ql/s3ql/blob/master/src/s3ql/umount.py#L97), I have to make sure myself that the main s3ql daemon has really finished after calling `umount.s3ql` (e.g., by calling `wait <pid>` after calling `umount.s3ql`).

My first thought was that getting the command line could also be accomplished with looking at `/proc/<PID>/cmdline`, but I guess that would not be compatible with OS X anymore? Maybe umount.s3ql could first look for `/proc` and only use `ps -p` as a backup if no procfs is available?

Alternatively, I would request to redirect stderr of the `ps` call to `/dev/null`, so BusyBox does at least not clutter my s3ql logs with log messages saying it does not support the `-p` flag.

**Comment by Nikratio** [comment]
Thanks for the report! I could imagine trying to look at `/proc` and falling back on `ps` if that doesn't exist - patches welcome :-).
