### ISSUE TITLE
Documentation for most commands mentions non-supported `--log` option

### ISSUE THREAD

**Issue by stjosh** [s3ql/s3ql#82]
Documentation for `umount.s3ql` is mentioning a `--log` option in the description of the `--debug` option:

- `umount.s3ql --help`
- [Unmounting](http://www.rath.org/s3ql-docs/umount.html)
- [`umount.s3ql` manpage](http://www.rath.org/s3ql-docs/man/umount.html)

However, `umount.s3ql` fails when supplied with `--log`, it  [does not support this flag](https://github.com/s3ql/s3ql/blob/master/src/s3ql/umount.py#L23). The mention of `--log` in the help messages comes from [here](https://github.com/s3ql/s3ql/blob/master/src/s3ql/parse_args.py#L154).

I think there are two approaches to resolve this:

- Add a `--log` option to `umount.s3ql` as well (I think this would make sense anyway - is there a specific reason for not supporting it?)
- Find a way to exclude [`destnote`](https://github.com/s3ql/s3ql/blob/master/src/s3ql/parse_args.py#L154) from the help message if the `--log` option is not supported

@Nikratio I'll gladly provide a Pull Request once you let me know which approach is preferred from your perspective.

**Comment by Nikratio** [comment]
Thanks for the report! I think we should add `--log` to umount.

**Comment by stjosh** [comment]
I just noticed that this is not specific for `umount.s3ql` only - any command having a `--debug` option but no `--log` option suffer the same misleading documentation and will refuse to work when supplied with `--log`:

- [mkfs](http://www.rath.org/s3ql-docs/man/mkfs.html)
- [verify](http://www.rath.org/s3ql-docs/man/verify.html)
- [s3qlstat](http://www.rath.org/s3ql-docs/man/stat.html)
- [s3qlctrl](http://www.rath.org/s3ql-docs/man/ctrl.html)
- [s3qlcp](http://www.rath.org/s3ql-docs/man/cp.html)
- [s3qlrm](http://www.rath.org/s3ql-docs/man/rm.html)
- [s3qllock](http://www.rath.org/s3ql-docs/man/lock.html)
- [s3ql_oauth_client](http://www.rath.org/s3ql-docs/man/oauth_client.html)
- [s3ql_verify](http://www.rath.org/s3ql-docs/man/verify.html)
- [pcp](http://www.rath.org/s3ql-docs/man/pcp.html)
- [expire_backups](http://www.rath.org/s3ql-docs/man/expire_backups.html)

So, #88 won't fix the whole issue (although I still think it makes sense to have it there). @Nikratio what do you propose for all the other commands? Adding `--log` everywhere, or somehow making sure `--log` is only mentioned in the documentation if the parameter is actually accepted?

**Comment by Nikratio** [comment]
I don't think this is a big issue. How about simply changing the description to say something like "..written to the target specified by --log or (if that option isn't available) to stdout"? I'm not opposed to adding --log everywhere, but as I said, I don't see the current situation to be a big problem.

**Comment by stjosh** [comment]
I fully agree that this is not a big problem. Just stumbled over it when trying to specify a log destination for umount and now noticed that it's not at all umount specific.

Personally, I think it would not hurt to add the log parameter to every command. If the default remains stdout, it's fully backwards compatible, so most people won't notice. Nevertheless, there might be cases here and there where one wants to specify a different log destination, so I'd consider it a nice move to give users this flexibility in case they need it. I'll open another PR in the next few days to add `--log` to all commands mentioned above. In case you disagree and are not interested in such a PR, feel free to let me know by closing this issue.
