### ISSUE TITLE
Update minimum required pytest version

### ISSUE THREAD

**Issue by macropin** [s3ql/s3ql#86]
The tests are failing with the following error with the 3.0 release:

```
============================= test session starts ==============================
platform linux -- Python 3.5.3, pytest-3.0.6, py-1.4.32, pluggy-0.4.0 -- /usr/bin/python3
cachedir: tests/.cache
rootdir: /tmp/tmp.2ZPMsLJWjt/tests, inifile: pytest.ini
plugins: catchlog-1.2.2
collecting ... 
==================================== ERRORS ====================================
_______________________ ERROR collecting t1_backends.py ________________________
tests/t1_backends.py:113: in pytest_generate_tests
    with_backend_mark = metafunc.definition.get_closest_marker('with_backend')
E   AttributeError: 'Metafunc' object has no attribute 'definition'
!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 1.21 seconds ============================
The command '/bin/sh -c /build-s3ql.sh' returned a non-zero code: 2
make: *** [build] Error 2
```

See https://github.com/panubo/docker-s3ql/blob/master/build-s3ql.sh for the complete installation / build script.

**Comment by Nikratio** [comment]
Thanks for the report! Please use pytest 4.x

**Comment by macropin** [comment]
Thanks. This is confirmed. Pytest 4.x works. 

May I suggest the following:

- Update the [documentation](http://www.rath.org/s3ql-docs/installation.html#dependencies) currently it reads `"pytest, version 2.7 or newer (optional, to run unit tests)"`
- Please consider adding the test requirements ie `tests_require` to `setup.py` and defining the test suite entry point there.
