### ISSUE TITLE
contrib/benchmark.py calls mkfs.s3ql with non-existing --force option

### ISSUE THREAD

**Issue by ajaraptor** [s3ql/s3ql#95]
Test file size: 1G from /dev/urandom
Written to cleared AWS S3 bucket

Got (with private data redacted):
mkfs.s3ql: error: unrecognized arguments: --force
ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "./benchmark.py", line 224, in <module>
    main(sys.argv[1:])
  File "./benchmark.py", line 96, in main
    '--quiet', '--force', '--cachedir', options.cachedir])
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mkfs.s3ql', '--plain', 'local:///tmp/s3ql-benchmark-ljlsxxsh', '--quiet', '--force', '--cachedir', '/root/.s3ql']' returned non-zero exit status 2.

(Newer version --with log flag, same error but on line 97)

**Comment by Nikratio** [comment]
Fixed in commit 4537700
