### ISSUE TITLE
error response not used in gs backend

### ISSUE THREAD

**Issue by andrewchambers** [s3ql/s3ql#96]
This issue is a continuation of a conversation in a closed/outdated pull request to ensure it is not lost.

https://github.com/s3ql/s3ql/blob/3b6295b6a5d8b64ce49163a7e6fd439391e2cd40/src/s3ql/backends/gs.py#L892

Does not handle the error response returned by :

https://github.com/s3ql/s3ql/blob/3b6295b6a5d8b64ce49163a7e6fd439391e2cd40/src/s3ql/backends/gs.py#L429

**Comment by Nikratio** [comment]
Thanks! Fixed in commit c1dd1
