### ISSUE TITLE
s3ql_oauth_client exits with error 400 Bad Request ("error": "invalid_scope")

### ISSUE THREAD

**Issue by tinmrn** [s3ql/s3ql#99]
Hello all,

When I tried to get a token for Google Storage oauth2, the s3ql_oauth_client fails with error:

```
# s3ql_oauth_client --version
S3QL 3.0

# s3ql_oauth_client --debug
2019-03-23 10:03:49.471 22967 DEBUG    MainThread s3ql.oauth_client._log_response: Server response:
400 Bad Request
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Date: Sat, 23 Mar 2019 09:03:49 GMT
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Pragma: no-cache
Content-Type: application/json; charset=utf-8
Vary: Origin, X-Origin, Referer
Content-Encoding: gzip
Server: ESF
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Alt-Svc: quic=":443"; ma=2592000; v="46,44,43,39"
Transfer-Encoding: chunked

{
  "error": "invalid_scope"
}
2019-03-23 10:03:49.474 22967 ERROR    MainThread root.excepthook: Connection failed with: 400 Bad Request
```

But looking at the source and the Google docs, the token https://www.googleapis.com/auth/devstorage.full_control should be a valid one: https://developers.google.com/identity/protocols/googlescopes

What could be wrong here?

**Comment by Nikratio** [comment]
Turns out this was a change at Google's end - the authentication workflow that S3QL uses is no longer supported to get "full access".

**Comment by tinmrn** [comment]
Allright. Not such a big problem anymore I guess now that ADC works well.
